#include "header.h"
#include <iostream>
#include <thread>
#include <chrono>

using namespace std;

bool win_or_lose;
//每關開始前先enter，再set_start true
//每關結束後先set_complete true再minus_health再confirm_land_conflict，再進main_menu

void opening() {
	cout << "本遊戲的劇情參考神奇寶貝動畫第五季改編\n\n";
	cout << "人類和寶可夢互相協調，組成了這個世界\n人們微笑的話，寶可夢也會微笑\n寶可夢難過時，人們也會難過\n\n這裡是卡洛斯地區，也是你即將展開冒險的地方。\n\n";
	my_cout("（按enter鍵繼續）");
	my_cout("\n[你]：皮卡丘你看到了嗎？從這裡下去之後就是紀念踏入卡洛斯的第一步喔！");
	my_cout("[皮卡丘]：皮卡皮卡");
	my_cout("\n~~~~故事開始~~~~");
}

void mission1_1()
 {//啟程 卡洛斯聯盟
	enter_mission(0, 0);
	missions[0][0].set_start(true);
	string yourname, yourtown;
	cout << "\n~~~~~主線第一章 開始~~~~~\n";
	cin.ignore();
	my_cout("[你]：既然來到密阿雷市，就先去挑戰密阿雷的道館吧！");
	my_cout("[皮卡丘]：皮卡皮卡");
	cout << "\n  [HINT]\n  道館對戰是訓練家對戰的一種形式。每座城市通常會有一座道館，訓練家可以上門挑戰各個道館的館主。\n";
	cout << "  每座道館有各自的屬性，該道館的館主在與挑戰者對戰時會使用該屬性的寶可夢。\n";
	my_cout("  挑戰者在道館戰中勝利可獲得一枚道館徽章。累積八枚道館徽章即可挑戰卡洛斯聯盟賽。");
	my_cout("\n[你]：道館居然在城市最高的塔裡頭，真不愧是密阿雷市！");
	my_cout("[謎之音]：歡迎來到密阿雷道館！");
	cout << "[你]：你好！我是......\n\n請輸入你的名字：";
	cin >> yourname;
	cout << "請問你來自哪裡："; cin >> yourtown;
	player.set_name(yourname); player.set_location(yourtown);
	cout << "\n[你]：我是來自" << player.get_loc() << "的" << player.get_name() << "！";
	cin.ignore(); cin.ignore();
	my_cout("[謎之音]：有幾個徽章呢？");
	my_cout("[你]：徽章？這個道館是初次挑戰，所以我還沒有徽章！");
	my_cout("[謎之音]：0個？挑戰密阿雷道館最少需要擁有四個徽章。請下次再來");
	my_cout("\n[此時你感覺到了一陣酥麻感從脊椎直上頭頂。回過神來，你已經被道館「丟」出稜鏡塔了]");
	cout << "請原地休息5秒\n";
	this_thread::sleep_for(chrono::seconds(5));
	my_cout("\n[少年]：你還好嗎？醒醒啊！");
	my_cout(".\n.\n.\nTo be continued...");
	my_cout("\n[主線1-1 啟程 密阿雷道館 completed]");
	my_cout("[獲得獎勵 體力、飢餓度、口渴度補滿]");
	my_cout("[已解鎖 查看玩家檔案]");
	cout << endl;
	missions[0][0].set_complete(true);
	main_menu();
}
void mission1_2() {//對戰 希特隆與掘掘兔
	enter_mission(0, 1);
	missions[0][1].set_start(true);
	my_cout("\n[你]：皮卡丘！皮卡丘呢？");
	cin.ignore();
	my_cout("[小女孩]：皮卡丘在這裡！");
	my_cout("[少年]：皮卡丘掉下來時被我妹妹接住了，倒是你，有受傷嗎？");
	my_cout("[你]：沒有，謝謝你！");
	my_cout("[你]：話說回來，這個道館怎麼回事啊？");
	my_cout("[少年]：你也被趕出來了呢");
	my_cout("[你]：好不容易來了，到底怎麼回事啊這裡的館主");
	my_cout("[小女孩]：密阿雷道館的館主是個很難對付的傢伙喔。對了，有問你有幾個徽章嗎？");
	my_cout("[你]：問了。我說還沒有，他一下就電過來了");
	my_cout("[小女孩]：咦！還沒有嗎？");
	cout << "[你]：我才剛剛到卡洛斯地區。還沒向你們自我介紹呢！我是來自" << player.get_loc() << "的" << player.get_name() << "。現在跟夥伴皮卡丘一起旅行，目標是成為寶可夢大師！";
	cin.ignore();
	my_cout("[皮卡丘]：皮卡皮卡");
	my_cout("[少年]：那麼我們也來自我介紹吧！我叫希特隆，這是我妹妹");
	my_cout("[小女孩]：我叫柚麗嘉");
	my_cout("[你]：希特隆、柚麗嘉，請多指教！對了，你們也在挑戰道館嗎？");
	my_cout("[希特隆]：呃...我們...");
	my_cout("[柚麗嘉]：我們這之後才要開始呢！");
	my_cout("[你]：真棒啊！兄妹一起旅行。希特隆，你有什麼樣的寶可夢呢？");
	my_cout("[希特隆]：有最近剛收服的......");
	my_cout("[你]：我想看我想看！不如我們來戰鬥吧！");

	my_cout("\n     [battle v.s. 希特隆]");
	pokemon* assign[1] = { &Bunnelby };
	win_or_lose = whole_battle(1, 1, &Clemont, assign);
	while (win_or_lose == false) {
		cout << "再試一次吧！\n";
		win_or_lose = whole_battle(1, 1, &Clemont, assign);
	}
	Bunnelby.set_new_value(100, 22, 5);
	cout << "\n[柚麗嘉]：不愧是" << player.get_name() << "和皮卡丘，果然是好夥伴呢！"; cin.ignore();
	my_cout("\n[突然有一個不明物體從天外朝皮卡丘飛來，皮卡丘迅速躲開]");
	my_cout("\n[你]：皮卡丘，你沒事吧！");
	my_cout("[皮卡丘]：皮卡皮卡");
	my_cout("[希特隆]：是誰？");
	my_cout(".\n.\n.\nTo be continued...");
	my_cout("\n[主線1-2 對戰 希特隆與掘掘兔 completed]");
	my_cout("[獲得獎勵：體力、飢餓度、口渴度、寶可夢HP補滿]");
	Pikachu.set_HP(Pikachu.get_max_HP());
	current_mission = &missions[0][2];
	missions[0][1].set_complete(true);
	confirm_land_conflict();
	main_menu();
}
void mission1_3() {//R是Rocket的意思
	current_mission = &missions[0][2];
	enter_mission(0, 2);
	missions[0][2].set_start(true);
	cin.ignore();
	my_cout("\n[邪魅女聲]：既然你誠心誠意地發問了！");
	my_cout("[邪魅男聲]：那我就大發慈悲地告訴你");
	my_cout("[邪魅女聲]：為了防止世界被破壞");
	my_cout("[邪魅男聲]：為了守護世界的和平");
	my_cout("[邪魅女聲]：貫徹愛與真實的邪惡");
	my_cout("[邪魅男聲]：可愛又迷人的反派角色");
	my_cout("[邪魅女聲]：武藏！");
	my_cout("[邪魅男聲]：小次郎！");
	my_cout("[邪魅女聲]：我們是穿梭在宇宙間的火箭隊二人組");
	my_cout("[邪魅男聲]：白洞，白色的明天正等著我們");
	my_cout("[邪魅喵聲]：就是這樣喵~");
	my_cout("[你]：火箭隊！你們也到卡洛斯地區了");
	my_cout("[希特隆]：喵喵居然會說話！");
	my_cout("[你]：等一下，希特隆。他們是一群喜歡搶別人寶可夢的壞傢伙，已經覬覦我的皮卡丘很久了！");
	my_cout("[希特隆]：欸！");
	my_cout("[武藏]：小鬼頭，你說錯了。我們覬覦的不是你的皮卡丘，而是卡洛斯地區所有珍稀的寶可夢");
	my_cout("[小次郎]：我們這次一定要抓到皮卡丘。果然翁，出來吧");

	my_cout("\n     [battle v.s. 火箭隊]");
	pokemon* assign[1] = { &Wobbuffet };
	win_or_lose = whole_battle(1, 1, &Rocket, assign);
	if (win_or_lose == false) {
		choose_one_pokemon = NULL;
		my_cout("[你]：皮卡丘！你還好嗎？");
		my_cout("[皮卡丘]：皮卡皮卡");
		my_cout("[希特隆]：是果然翁的鏡面反射，他能把承受的攻擊還給皮卡丘，還是先撤退吧");
		my_cout("[你]：不。我們一直都是都是直面面對的，這次也不例外");
		my_cout("[你]：只要皮卡丘還沒放棄，我就會跟這傢伙一起戰鬥");
		my_cout("[皮卡丘]：皮卡皮卡");
		my_cout("[小次郎]：不管來幾次都一樣");
		my_cout("[你]：皮卡丘，使出電球！");
		my_cout("[希特隆]：掘掘兔，用泥巴噴射");
		my_cout("[皮卡丘 使出 電球]");
		my_cout("[掘掘兔 使出 泥巴噴射]");
		my_cout("[武藏]：果然翁，使出鏡面反射");
		my_cout("[果然翁 使出 鏡面反射]");
		my_cout("[你]：皮卡丘！！！！！");
		my_cout("\n[此時有一道藍色身影快速閃過，擋下了果然翁的攻擊]");
		my_cout("\n[你]：皮卡丘！沒事吧");
		my_cout("[皮卡丘]：皮卡皮卡");
		my_cout("[你]：他是...");
		my_cout("[希特隆]：是呱呱泡蛙！卡洛斯地區的新人用寶可夢之一");
		my_cout("[呱呱泡蛙]：Gero");
		my_cout("[你]：謝謝你，呱呱泡蛙");
		my_cout("[希特隆]：但他是水系，受到電系招的反彈......");
		my_cout("[呱呱泡蛙]：Ge...ro...");
		my_cout("[你]：你還好嗎？呱呱泡蛙");
		my_cout("[呱呱泡蛙]：Gero!");
		my_cout("[武藏]：什麼阿這傢伙");
		my_cout("[你]：你要幫我們嗎？");
		my_cout("[呱呱泡蛙]：GeroGero GeroGero");
		my_cout("[喵喵]：他說「壞傢伙不可原諒」");
		my_cout("[呱呱泡蛙 使出 泡沫]");
		my_cout("[你]：我們上吧，皮卡丘");
		my_cout("[希特隆]：掘掘兔，我們也上，使出挖洞");
		my_cout("[掘掘兔 使出 挖洞]");
		my_cout("[火箭隊腳下的地面因為掘掘兔的挖洞裂開了]");
		my_cout("[火箭隊]：啊啊啊啊~~~~~");
		my_cout("[你]：再給他一擊，皮卡丘，十萬伏特");
		my_cout("[皮卡丘 使出 十萬伏特]");
		my_cout("[呱呱泡蛙 使出 水之波動]");
		my_cout("[火箭隊]：啊啊啊啊~~~~~好討厭的感覺！！！！！");
		my_cout("[柚麗嘉]：哇！好大的威力");
		my_cout("[你]：各位，謝謝你們了");
		my_cout("[呱呱泡蛙]：Ge...ro...");
		my_cout("[你]：呱呱泡蛙！");
		my_cout("[希特隆]：得趕緊治療，送他去普拉塔諾博士的實驗室吧！");
		my_cout("[柚麗嘉]：我帶路，往這邊");
		my_cout(".\n.\n.\nTo be continued...");
		my_cout("\n[主線1-3 R是Rocket的意思 completed]");
		my_cout("[獲得獎勵：飢餓度、口渴度補滿，寶可夢HP補滿]");
		Pikachu.set_HP(Pikachu.get_max_HP() - Pikachu.get_HP());
		my_cout("[已解鎖 火箭隊雷達]");
		missions[0][2].set_complete(true);
		player.minus_tiredness(5);
		confirm_land_conflict();
		main_menu();
	}
}
void mission1_4() {//mega進化 普拉塔諾博士與烈咬陸鯊
	enter_mission(0, 3);
	missions[0][3].set_start(true);
	cin.ignore();
	my_cout("[你]：不好意思！請問普拉塔諾博士在嗎？");
	my_cout("[普拉塔諾博士]：什麼事？");
	my_cout("[普拉塔諾博士]：呱呱泡蛙！快，送他去治療");
	my_cout("[研究員]：是");
	my_cout("[你]：咦？您知道這隻呱呱泡蛙嗎？");
	my_cout("[普拉塔諾博士]：沒錯，這隻呱呱泡蛙是從我這兒送出去的新手訓練家用寶可夢");
	my_cout("[你]：那聯絡上他的訓練家了嗎？");
	my_cout("[普拉塔諾博士搖搖頭]");
	my_cout("[普拉塔諾博士]：其實這隻呱呱泡蛙已經被很多名訓練家退回了。說他總是不聽從指示、擅自停止戰鬥。");
	my_cout("[希特隆]：擅自離開戰鬥？");
	my_cout("[你]：呱呱泡蛙現在在哪兒呢？");
	my_cout("[普拉塔諾博士]：他在治療室裡頭接受治療");
	my_cout("[普拉塔諾博士]：放心，我們的研究員都很專業的！");
	my_cout("[烈咬陸鯊]：gaga");
	my_cout("[你]：是烈咬陸鯊！");
	my_cout("[普拉塔諾博士]：我們這兒的烈咬陸鯊，是個個性不錯的孩子。");
	cout << "[普拉塔諾博士]：烈咬陸鯊，呱呱泡蛙沒事囉！都是多虧" << player.get_name() << "他們";
	cin.ignore();
	my_cout("[烈咬陸鯊]：gaga");
	my_cout("[你]：請多指教囉，烈咬陸鯊！你真溫柔呢，已經沒事了");
	my_cout("[烈咬陸鯊]：gaga");
	my_cout("[希特隆]：博士，您的研究是寶可夢的進化對吧！");
	my_cout("[普拉塔諾博士]：沒錯！研究所裡還有許多寶可夢，去看看吧！烈咬陸鯊，你能在這兒協助照顧一下呱呱泡蛙嗎？");
	my_cout("[烈咬陸鯊]：gaga");
	my_cout("\n[柚麗嘉]：哇！是三蜜蜂！還有電蜥蜴！");
	my_cout("[你]：博士，請問進化的研究是什麼呢？");
	my_cout("[普拉塔諾博士]：如果說，大家認為寶可夢另一階段的進化，你相信嗎？");
	my_cout("    [HINT]\n    進化是指寶可夢在某些機遇時刻下，會產生型態的變化。\n    其屬性可能會改變、也可能在進化過程中學會新的招式。");
	my_cout("[你]：另一階段的進化？");
	my_cout("[希特隆]：烈咬陸鯊還能再進化嗎？");
	my_cout("[普拉塔諾博士]：有這種可能性。目前已經發現幾個類似的案例，這在研究者之間被稱為mege進化");
	my_cout("[普拉塔諾博士]：這個學論還有許多謎團。但普遍認為，mega進化需要特殊的石頭，以及寶可夢與訓練家之間強烈的羈絆。");
	my_cout("[普拉塔諾博士]：最令人震驚的是，即使寶可夢進化了也能回復原來的樣子。");
	my_cout("[你]：回復原來的樣子？");
	my_cout("[突然遠方傳來一陣劇烈的叫聲]");
	my_cout("[普拉塔諾博士]：是烈咬陸鯊！");
	my_cout("[希特隆]：我們快趕過去吧");
	my_cout("\n[你]：烈咬陸鯊！發生什麼事了");
	my_cout("[研究員]：剛剛那群怪人近來研究中心，說是要協助研究的人員。我一說要向博士確認，他們便向呱呱泡蛙丟擲奇怪的不明物體。烈咬陸鯊為了救呱呱泡蛙，脖子上反而被不明的金屬項圈套住了");
	my_cout("[柚麗嘉]：烈咬陸鯊看起來很痛苦");
	my_cout("[你]：你們到底是誰？");
	my_cout("[武藏]：既然你誠心誠意的發問了！");
	my_cout("[小次郎]：我就大發慈悲的告訴你");
	my_cout("[武藏]：為了防止世界被破壞");
	my_cout("[小次郎]：為了守護世界的和平");
	my_cout("[武藏]：貫徹愛與真實的邪惡");
	my_cout("[小次郎]：可愛又迷人的反派角色");
	my_cout("[武藏]：武藏！");
	my_cout("[小次郎]：小次郎！");
	my_cout("[武藏]：我們是穿梭在宇宙間的火箭隊二人組");
	my_cout("[小次郎]：白洞，白色的明天正等著我們");
	my_cout("[喵喵]：就是這樣喵~");
	my_cout("[希特隆]：火箭隊！又是你們！");
	my_cout("[喵喵]：烈咬陸鯊我們就收下啦喵~");
	my_cout("[烈咬陸鯊]：gaga——gaga——");
	my_cout("[小次郎]：不該是這樣的啊......");
	my_cout("[烈咬陸鯊大吼一聲，使出破壞光線，正好射向了火箭隊]");
	my_cout("[火箭隊]：好討厭的感覺啊~~~");
	my_cout("[烈咬陸鯊]：gaga——gaga——");
	my_cout("[烈咬陸鯊瞳孔發紅，失控地飛向研究所門外]");
	my_cout("[希特隆]：糟了，烈咬陸鯊現在朝稜鏡塔去，照他現在的狀況，肯定會造成密阿雷市中心大亂");
	my_cout("[普拉塔諾博士]：快聯絡君莎小姐");
	my_cout("    [HINT]\n    君莎小姐是寶可夢世界裡的警察");
	my_cout("[你]：我們先過去看看吧");
	my_cout("[呱呱泡蛙]：GeroGero");
	my_cout("[你]：呱呱泡蛙，你也要去嗎？");
	my_cout("[呱呱泡蛙]：Gero");
	my_cout("[柚麗嘉]：哥哥我們也去吧");
	my_cout("\n[稜鏡塔]");
	my_cout("[記者]：記者目前位置所在密阿雷市稜鏡塔。方才突然有隻烈咬陸鯊因不明原因而發狂，已破壞好幾處街道，請附近的民眾小心安全...");
	my_cout("[柚麗嘉]：烈咬陸鯊現在在塔上");
	my_cout("[你]：皮卡丘");
	my_cout("[皮卡丘]：皮卡皮卡");
	my_cout("[希特隆]：等等，你們要爬上去嗎？");
	my_cout("[你]：烈咬陸鯊在哭泣，我不能見死不救");
	my_cout("[希特隆]：......");
	my_cout("[希特隆]：我知道哪裡可以上去，跟我來");
	my_cout("[你]：謝謝你，希特隆");
	my_cout("[希特隆領著一行人走到稜鏡塔某處小門邊]");
	my_cout("[希特隆]：希特隆引擎，啟動！");
	my_cout("[只見希特隆的後背包裡伸出一隻機器手臂，在門上的面板進行一連串操作號，門便順利打開了]");
	my_cout("[你]：好厲害");
	my_cout("[希特隆]：快進去吧");
	my_cout("[你走進塔內，突然一塊磚牆從高處掉落，將希特隆兄妹倆與你相阻隔");
	my_cout("[你]：希特隆！柚麗嘉！你們還好嗎？");
	my_cout("[希特隆]：我們沒事。你先上去幫助烈咬陸鯊吧");
	my_cout("[稜鏡塔塔頂]");
	my_cout("[烈咬陸鯊]：gaga——");
	my_cout("[你]：烈咬陸鯊，我來了");
	my_cout("[烈咬陸鯊使出破壞光線，你為了躲避而摔倒在地]");
	my_cout("[你]：烈咬陸鯊，你聽得見嗎？");
	my_cout("[你]：大家都很擔心你，來吧，我幫你把項圈取下來，回到大家身邊吧");
	my_cout("[烈咬陸鯊]：gaga——");
	my_cout("[你]：好嗎，烈咬陸鯊？");
	my_cout("[烈咬陸鯊痛苦得全身顫抖。他不斷向後退，只見他的腳步離掉下稜鏡塔只有咫尺之距]");
	my_cout("[你]：烈咬陸鯊！");
	my_cout("[呱呱泡蛙使出泡沫，將烈咬陸鯊的腳黏在稜鏡塔上]");
	my_cout("[你]：呱呱泡蛙，做得好！");
	my_cout("[你]：皮卡丘，對項圈使出鐵尾");
	my_cout("[皮卡丘使出鐵尾，烈咬陸鯊脖子上的項圈應聲斷裂]");
	my_cout("[你]：烈咬陸鯊，還好嗎？");
	my_cout("[烈咬陸鯊]：gaga");
	my_cout("[你]：太好了，我們回去吧");
	my_cout("\n[普拉塔諾博士研究所]");
	my_cout("[普拉塔諾博士]：烈咬陸鯊！");
	my_cout("[烈咬陸鯊]：gaga");
	my_cout("[普拉塔諾博士]：太好了！謝謝你們的幫忙");
	my_cout("[你]：只要烈咬陸鯊沒事就好了");
	my_cout("[烈咬陸鯊]：gaga");
	my_cout("[普拉塔諾博士]：還是得感謝你們");
	cout << "[普拉塔諾博士]：對了，" << player.get_name();
	my_cout("你是不是馬上就要展開旅行了？");
	my_cout("[你]：沒錯！待會就跟皮卡丘一起出發");
	my_cout("[皮卡丘]：皮卡皮卡");
	my_cout("[普拉塔諾博士]：我替你準備一些旅途上可能用的到的東西吧！也算是為了答謝你救了烈咬陸鯊！");
	my_cout("[你]：謝謝您！");
	my_cout("[呱呱泡蛙]：Gero GeroGero");
	my_cout("[普拉塔諾博士]：怎麼了，呱呱泡蛙？");
	my_cout(".\n.\n.\nTo be continued...");
	my_cout("\n[主線1-4 mega進化 普拉塔諾博士與烈咬陸鯊 completed]");
	my_cout("[獲得獎勵：玩家初始裝備]");
	my_cout("[寶可夢經驗值上升]");
	minus_health();
	my_cout("[已解鎖 我的背包]");
	missions[0][3].set_complete(true);
	confirm_land_conflict();
	main_menu();
}
void mission1_5() {//挑戰開始 前進白檀市
	enter_mission(0, 4);
	missions[0][4].set_start(true);
	cin.ignore();
	my_cout("[呱呱泡蛙蹲在一顆寶貝球旁，下巴頂了頂寶貝球]");
	my_cout("[普拉塔諾博士]：原來呱呱泡蛙還會自己選訓練家呢");
	my_cout("[皮卡丘]：皮卡皮卡");
	my_cout("[你]：呱呱泡蛙，你想跟我一起去旅行嗎？");
	my_cout("[呱呱泡蛙]：gero");
	my_cout("[你]：那就......");
	my_cout("[你拿起寶貝球，碰了碰呱呱泡蛙的頭頂。寶貝球上的圓圈閃了三下，便不再動了]");
	Froakie.be_catched(true);
	my_cout("[你]：成功收服呱呱泡蛙了！");
	my_cout("[皮卡丘]：皮卡皮卡");
	my_cout("[希特隆]：恭喜你！");
	my_cout("[希特隆]：對了，你決定接下來要去挑戰哪個道館了嗎？");
	my_cout("[你]：還沒耶。希特隆有推薦的地方嗎？");
	my_cout("[希特隆]：不如先去白檀道館吧！雖然館主碧歐拉小姐很不好對付，但相信你一定可以的！");
	my_cout("[你]：謝謝你，希特隆！");
	my_cout("[你]：那麼，皮卡丘，開始旅程囉");
	my_cout("[皮卡丘]：皮卡皮卡");
	my_cout("[希特隆、柚麗嘉、普拉塔諾博士]：一路順風！");
	my_cout("\n[在密阿雷市經歷了一連串事件，你與夥伴們的旅程還將繼續。]");
	my_cout(".\n.\n.\nTo be continued...");
	my_cout("\n[主線1-5 挑戰開始 前進白檀市 completed]");
	my_cout("[獲得獎勵：銀莓果*3，三明治*3]");
	player.get_consumable(2)->add_num(3); player.get_consumable(5)->add_num(3);
	my_cout("[寶可夢經驗值上升]");
	minus_health();
	missions[0][4].set_complete(true);
	confirm_land_conflict();
	main_menu();
}

void mission2_1() {//呱呱泡蛙與小箭雀
	enter_mission(1, 0);
	if (missions[1][0].get_start() == false) {
		missions[1][0].set_start(true);
		cin.ignore();
		my_cout("\n~~~~~主線第二章 開始~~~~~");
		my_cout("\n[你]：呱呱泡蛙，出來吧");
		my_cout("[呱呱泡蛙]：gero");
		my_cout("[皮卡丘]：皮卡皮卡");
		my_cout("[你]：這座森林有好多特別的樹果阿！");
		my_cout("[皮卡丘]：皮卡皮卡");
		my_cout("[皮卡丘用尾巴比了比樹上的藍色樹果]");
		my_cout("[呱呱泡蛙]：gerogero");
		my_cout("[呱呱泡蛙一躍到樹上，摘了一串藍色樹果放到皮卡丘面前]");
		my_cout("[皮卡丘]：皮卡皮卡");
		my_cout("[呱呱泡蛙]：gero");
		my_cout("[突然有一道小小的橘色身影從皮卡丘身前飛過，倏忽間就叼走了樹果]");
		my_cout("[呱呱泡蛙]：gero gerogero");
		my_cout("[你]：那是...小箭雀");
		my_cout("[小箭雀]：yako");
		my_cout("[呱呱泡蛙]：gerogero");
		my_cout("[呱呱泡蛙對小箭雀使出泡沫，小箭雀敏捷地一一躲開]");
		my_cout("[你]：這隻小箭雀的機動力真是不錯...");
		my_cout("[你]：好，我決定了，我要收服他");
		my_cout("[小箭雀]：yako");
	}

	my_cout("\n     [battle v.s. 小箭雀]");
	pokemon* assign[1] = { &Fletchling };
	win_or_lose = whole_battle(1, 1, NULL, assign);
	if (win_or_lose == false) {
		cout << "再鍛鍊鍛鍊寶可夢吧！\n";
		main_menu();
		mission2_1();
	}
	if (missions[1][0].get_complete() == false) {
		use_my_pokemon_ball();
		cin.ignore();
		Fletchling.be_catched(true);
		my_cout("[你]：成功收服小箭雀了！");
		my_cout("[呱呱泡蛙]：gerogero");
		my_cout("[皮卡丘]：皮卡皮卡");
		my_cout("[你]：我和你們、和小箭雀一起，去挑戰白檀道館吧！");
		my_cout(".\n.\n.\nTo be continued...");
		my_cout("\n[主線2-1 呱呱泡蛙與小箭雀 completed]");
		my_cout("[獲得獎勵：銀莓果*3，好傷藥*5]");
		player.get_consumable(2)->add_num(3); player.get_consumable(8)->add_num(5);
		my_cout("[寶可夢經驗值上升]");
		minus_health();
		my_cout("[已解鎖 我的寶可夢]");
		my_cout("[已解鎖 屬性剋制表]");
		missions[1][0].set_complete(true);
		confirm_land_conflict();
		main_menu();
	}
}
void mission2_2() {//挑戰白檀道館 溜溜糖球與彩粉蝶
	enter_mission(1, 1);
	if (missions[1][1].get_start() == false) {
		missions[1][1].set_start(true);
		cin.ignore();
		my_cout("[你]：這裡就是白檀道館");
		my_cout("[皮卡丘]：皮卡皮卡");
		my_cout("[神秘女士]：你跟你的皮卡丘感情很好呢！能讓我拍一張你們的照片嗎？");
		my_cout("[你]：可以呀");
		my_cout("[你]：請問您是誰呢？是攝影師嗎？");
		my_cout("[神秘女士]：嗯...這算是我的其中一個身分吧...");
		my_cout("[神秘女士]：拍好了！真是張好照片呢。再見啦");
		my_cout("[你]：好了皮卡丘，我們進去道館吧！");
		my_cout("[皮卡丘]：皮卡皮卡");
		my_cout("\n[白檀道館內]");
		cout << "[你]：你好！我是來自" << player.get_loc() << "的" << player.get_name();
		my_cout("，今天想要來挑戰道館");
		my_cout("[神秘女士]：你就是今天的挑戰者嗎？");
		my_cout("[你]：欸！您是剛剛在門外的...");
		my_cout("[神秘女士]：沒錯。重新自我介紹一下吧！我是碧歐拉，白檀道館的館主");
		my_cout("[碧歐拉]：事不遲宜，我們開始今天的道館戰吧！");
	}
	my_cout("\n     [battle v.s. 碧歐拉]");
	cout << "[對戰裁判員]：現在開始挑戰者" << player.get_name() << "與館主碧歐拉的對戰。";
	my_cout("使用的寶可夢為兩隻，若有一方的寶可夢全數失去戰鬥能力則對戰結束。只有挑戰者可進行寶可夢的替換。");
	my_cout("[碧歐拉]：像瞄準按下快門一樣瞄準勝利吧！去吧，溜溜糖球！");
	pokemon* assign[2] = { &Surskit, &Vivillon };
	win_or_lose = whole_battle(2, 2, &Viola, assign);
	if (win_or_lose == false) {
		cout << "再鍛鍊鍛鍊寶可夢吧！\n";
		main_menu();
		mission2_2();
	}
	if (missions[1][1].get_complete() == false) {
		my_cout("[對戰裁判員]：本場對戰由挑戰者獲勝！");
		my_cout("[碧歐拉]：恭喜！這是贏了我道館戰的徽章，昆蟲徽章。收下它吧！");
		my_cout("[你獲得 昆蟲徽章]");
		player.add_badge(badge("白檀道館", 11));
		player.plus_badgenum();
		my_cout("[你]：今天真的很謝謝您！");
		my_cout("[碧歐拉]：你決定好下個想去挑戰的道館了嗎？");
		my_cout("[你]：還沒耶！碧歐拉小姐有推薦的嗎？");
		my_cout("[碧歐拉]：你可以去遙香市，那兒的道館館主查克洛是個很有趣的人！");
		my_cout("[你]：好，那我們前往遙香市吧！");
		my_cout("[皮卡丘]：皮卡皮卡");
		my_cout(".\n.\n.\nTo be continued...");
		my_cout("\n[主線2-2 挑戰白檀道館 溜溜糖球與彩粉蝶 completed]");
		my_cout("[獲得獎勵：皮幣*500]");
		player.set_money(500);
		my_cout("[寶可夢經驗值上升]");
		minus_health();
		missions[1][1].set_complete(true);
		current_mission = &missions[1][2];
		confirm_land_conflict();
		main_menu();
	}
}
void mission2_3() {//密阿雷道館館主
	enter_mission(1, 2);
	missions[1][2].set_start(true);
	cin.ignore();
	my_cout("[你]：到了密阿雷市再繼續向西走，馬上就到遙香市囉！");
	my_cout("[皮卡丘]：皮卡皮卡");
	cout << "[熟悉男聲]：" << player.get_name() << "！"; cin.ignore();
	my_cout("[你一回到密阿雷市，便聽見背後傳來熟悉的聲音]");
	my_cout("[你]：希特隆！柚麗嘉！");
	my_cout("[希特隆]：又見面了呢！你挑戰白檀道館還順利嗎？");
	my_cout("[你]：嗯！我已經拿到第一個徽章了");
	my_cout("[柚麗嘉]：哇恭喜你！");
	my_cout("[神秘男聲]：希特隆！！！！！柚麗嘉！！！！！");
	my_cout("[你]：是電龍，還有......");
	my_cout("[希特隆、柚麗嘉]：爸爸！");
	my_cout("[希特隆爸爸]：好久不見啦！哈哈！");
	my_cout("[希特隆爸爸]：這位是...？");
	my_cout("[柚麗嘉]：這是我們的朋友");
	cout << "[你]：您好，我是來自" << player.get_loc() << "的" << player.get_name(); cin.ignore();
	my_cout("[希特隆爸爸]：希特隆和柚麗嘉交到朋友？我...我...真是太感動了");
	my_cout("[希特隆]：真是的，您別這樣");
	my_cout("[希特隆爸爸]：看到你們過得不錯我就安心了");
	my_cout("[希特隆爸爸]：但是，希特隆，我還是要提醒你，嚴厲對待訓練家是好，但光是嚴厲，是培養不出優秀訓練家的");
	my_cout("[希特隆]：嗯...");
	my_cout("[希特隆爸爸]：加油囉！我們引以為傲的密阿雷道館館主！下次見！");
	my_cout("[希特隆]：啊...呃...下次見");
	my_cout("[你]：希特隆你是...密阿雷道館的館主！？");
	my_cout("[希特隆]：啊...呃...這個");
	my_cout("[柚麗嘉]：哥哥，這瞞不住了");
	my_cout("[希特隆]：......我就是密阿雷道館的館主。抱歉，我並不是有意要隱瞞的");
	my_cout("[你]：那當時把我從道館裡扔出來的，那到底是怎麼回事啊？");
	my_cout("[希特隆]：那是史特洛伊德...我發明的機器人，也是代理館主");
	my_cout("[希特隆]：事情是這樣的。當上館主後的日子越來越忙，我平時喜歡的發明也沒有時間鑽研了。所以我就發明了史特洛伊德來幫忙處理館主的工作");
	my_cout("[希特隆]：但他的AI系統還沒有完全訓練好，對挑戰者沒有什麼耐心、什至會做出一些偏激的行為");
	my_cout("[希特隆]：更糟的是，我在設定聲音密碼時出了一些狀況，導致他沒有辦法辨認我是他的發明家，然後......");
	my_cout("[柚麗嘉]：然後我跟哥哥就像你們一樣，被史特洛伊德趕出道館了");
	my_cout("[你]：除了聲音密碼，沒有其他方式能讓他辨認出你嗎？");
	my_cout("[希特隆]：還有主人辨識戰鬥...但...");
	my_cout("[你]：既然有方法，去做就對了啊");
	my_cout("[希特隆]：可是史特洛伊德拿的是我的寶可夢，所以我知道，還不成熟的掘掘兔是沒辦法戰勝的");
	my_cout("[你]：戰鬥這種事，不試試怎麼會知道結果？希特隆你身為道館館主應該是最清楚的吧！");
	cout << "[柚麗嘉]：哥哥，我也認同" << player.get_name() << "說的，畢竟再這麼下去也不是辦法..."; cin.ignore();
	my_cout("[希特隆]：...你們說的對，而且史特洛依德是我發明的，我得負起責任才對");
	my_cout("\n[密阿雷道館內]");
	my_cout("[希特隆]：史特洛伊德，啟動主人辨識戰鬥系統");
	my_cout("[史特洛伊德]：主人辨識戰鬥系統啟動");
	my_cout("\n     [battle v.s. 史特洛伊德]");
	my_cout("\n[希特隆派出了 掘掘兔(一般)]");
	my_cout("[史特洛伊德派出了 光電傘蜥(一般、電)]");
	my_cout("[史特洛伊德]：上囉！十萬伏特！");
	my_cout("[光電傘蜥 使出 十萬伏特]");
	my_cout("[希特隆]：打招呼的十萬伏特...確實是我寫的程式碼");
	my_cout("[希特隆]：那就換我們了！掘掘兔，連環巴掌");
	my_cout("[掘掘兔 使出 連環巴掌]");
	my_cout("[史特洛伊德]：龍尾！");
	my_cout("[光電傘蜥 使出 龍尾]");
	my_cout("[希特隆]：掘掘兔，用挖洞");
	my_cout("[掘掘兔 使出 挖洞]");
	my_cout("[史特洛伊德]：用地流沙");
	my_cout("[光電傘蜥 使出 地流沙]");
	my_cout("[希特隆]：這種技能我沒教過光電傘蜥啊");
	my_cout("[你]：史特洛伊德竟然能讓光電傘蜥學會新招式，真厲害");
	my_cout("[希特隆]：掘掘兔，影分身");
	my_cout("[掘掘兔 使出 影分身]");
	my_cout("[史特洛伊德]：使出廣域充電！");
	my_cout("[光電傘蜥 使出 廣域充電，掘掘兔的影分身一下就被打散了]");
	my_cout("[希特隆]：掘掘兔，用挖洞");
	my_cout("[掘掘兔 使出 挖洞]");
	my_cout("[史特洛伊德]：地流沙！");
	my_cout("[光電傘蜥 使出 地流沙]");
	my_cout("[柚麗嘉]：再這樣下去就重蹈覆轍了！");
	my_cout("[你]：還沒結束呢，勝負不到最後不要放棄！");
	my_cout("[希特隆]：掘掘兔，在地面裡使用影分身！");
	my_cout("[掘掘兔 使出 影分身]");
	my_cout("[史特洛伊德]：使出廣域充電！");
	my_cout("[光電傘蜥 使出 廣域充電，掘掘兔的影分身再次被打散]");
	my_cout("[皮卡丘]：皮卡皮卡");
	my_cout("[你]：...原來是這樣啊！");
	my_cout("[史特洛伊德]：使出廣域充電！");
	my_cout("[光電傘蜥 使出 廣域充電，掘掘兔的影分身一下就被打散了]");
	my_cout("[此時，掘掘兔的本體從地面下竄出，正中光電傘蜥]");
	my_cout("[史特洛伊德]：光電傘蜥！");
	my_cout("[希特隆]：最後一擊！泥巴噴射！");
	my_cout("[掘掘兔 使出 泥巴噴射]");
	my_cout("[光電傘蜥失去戰鬥能力，希特隆贏得戰鬥]");
	my_cout("[希特隆]：光電傘蜥你沒事吧！");
	my_cout("[光電傘蜥]：barrera~");
	my_cout("[希特隆]：太好了！");
	my_cout("[史特洛伊德]：成功辨識為主人");
	my_cout("[史特洛伊德]：希特隆，歡迎回來");
	my_cout("[希特隆]：我回來了，史特洛伊德。因為我的錯誤你這段時間辛苦了！我來修改一下程序吧");
	my_cout("\n[希特隆]：終於修改好了！史特洛伊德，今後我們一起成長吧");
	my_cout("[史特洛伊德]：明白了");
	my_cout("[你]：希特隆！");
	my_cout("[希特隆]：謝謝你！如果不是你，事情大概沒辦法這麼順利");
	my_cout("[希特隆]：如果你想，現在也可以馬上挑戰道館喔！");
	my_cout("[你]：我還是等拿到四枚徽章後再來挑戰吧");
	my_cout("[你]：不過到時候，我想挑戰的不是史特洛伊德，而是希特隆你喔！");
	my_cout("[希特隆]：嗯，那麼祝你好運了！");
	my_cout("[你]：嗯！皮卡丘，我們繼續前進遙香市吧！");
	my_cout("[皮卡丘]：皮卡皮卡");
	my_cout(".\n.\n.\nTo be continued...");
	my_cout("\n[主線2-3 挑戰白檀道館 溜溜糖球與彩粉蝶 completed]");
	my_cout("[獲得獎勵：三明治*3，銀莓果*5]");
	player.get_consumable(2)->add_num(5); player.get_consumable(5)->add_num(3);
	my_cout("[寶可夢經驗值上升]");
	minus_health();
	missions[1][2].set_complete(true);
	current_mission = &missions[1][3];
	confirm_land_conflict();
	main_menu();
}
void mission2_4() {//挑戰遙香道館 封印岩石封鎖
	enter_mission(1, 3);
	if (missions[1][3].get_start() == false) {
		missions[1][3].set_start(true);
		cin.ignore();
		my_cout("[你]：道館在山頂上啊！");
		my_cout("[你走進山洞，眼前景象便猶如桃花源般的擴展開來。只是眼前所見並非落英繽紛，而是一個巨大的攀岩場。]");
		cout << "[你]：您好，我是來自" << player.get_loc() << "的" << player.get_name(); cin.ignore();
		my_cout("[你]：道館站就拜託您了！查克拉先生！");
		my_cout("[一名男人站在攀岩場的頂端，身上還穿著攀岩用的工具]");
		my_cout("[查克拉]：那還用說，自從聽碧歐拉提過你，我等了好久了！來吧！爬上來吧！");
		my_cout("[你]：咦？我得爬上去嗎？");
		my_cout("[查克拉]：對戰場地就在這頂端，想挑戰就上來吧！");
		my_cout("\n[你費了一番功夫終於爬上絕壁。]");
		my_cout("[查克拉]：沒想到你真的爬上來啦！剛剛攀岩時，你心裡在想什麼呢？");
		my_cout("[你]：我大概...什麼都沒想吧！");
		my_cout("[查克拉]：那你眼中注視著什麼呢？");
		my_cout("[你]：上面！我只看著上面");
		my_cout("[查克拉]：原來如此。你的心沒有一絲混濁，晶瑩剔透。");
		my_cout("[查克拉]：征服了絕壁之後還有我這個絕壁。請你征服我吧，挑戰者！");
	}

	my_cout("\n     [battle v.s. 查克拉]");
	my_cout("\n[對戰裁判員]：現在開始挑戰者" + player.get_name() + "與館主查克拉的對戰。");
	my_cout("[對戰裁判員]：使用的寶可夢為兩隻，若有一方的寶可夢全數失去戰鬥能力則對戰結束。只有挑戰者可進行寶可夢的替換。");
	my_cout("[查克拉]：你會用怎樣的戰鬥跨越我這道絕壁呢？讓我好好見識！去吧，大岩蛇！");
	pokemon* assign[2] = { &Onix, &Tyrunt };
	win_or_lose = whole_battle(2, 2, &Chakra, assign);
	if (win_or_lose == false) {
		cout << "再鍛鍊鍛鍊寶可夢吧！\n";
		main_menu();
		mission2_4();
	}
	if (missions[1][3].get_complete() == false) {
		my_cout("[對戰裁判員]：本場對戰由挑戰者獲勝！");
		my_cout("[你]：太好了！");
		my_cout("[查克拉]：真是一場灼熱的對戰阿！辛苦了，寶寶暴龍");
		my_cout("[查克拉]：你們成功地跨越了這道絕壁。這是其證明：岩石徽章");
		my_cout("[你獲得 岩石徽章]");
		player.add_badge(badge("遙香道館", 12));
		player.plus_badgenum();
		my_cout("[查克拉]：現在，讓我送你到道館門口吧！");
		my_cout("[你]：謝謝您！一樣要爬絕壁下去嗎？");
		my_cout("[查克拉]：不。其實那邊有電梯。");
		my_cout("[你]：咦！？");
		my_cout("[查克拉]：哈哈！對了，你決定接下來要去那兒挑戰道館站了嗎？");
		my_cout("[你]：我想沿著路走，到娑羅市去！");
		my_cout("[查克拉]：嗯！我就送到這兒，挑戰者，祝你好運啦！");
		my_cout("[你]：嗯。皮卡丘，我們走吧！");
		my_cout("[皮卡丘]：皮卡皮卡");
		my_cout("\n[經過兩場道館對戰，你與夥伴們間的關係變得更嘉緊密。而你們的旅程還將繼續。]");
		my_cout(".\n.\n.\nTo be continued...");
		my_cout("\n[主線2-4 挑戰遙香道館 封印岩石封鎖 completed]");
		my_cout("[獲得獎勵：皮幣*500]");
		player.set_money(500);
		my_cout("[寶可夢經驗值上升]");
		minus_health();
		missions[1][3].set_complete(true);
		current_mission = &missions[2][0];
		confirm_land_conflict();
		main_menu();
	}
}

void mission3_1() {//森林之王(收服摔跤鷹人)
	enter_mission(2, 0);
	if (missions[2][0].get_start() == false) {
		missions[2][0].set_start(true);
		cin.ignore();
		my_cout("\n~~~~~主線第三章 開始~~~~~");
		my_cout("[你]：通過這座森林後，我們就正式離開遙香市了！");
		my_cout("[皮卡丘]：皮卡皮卡");
		my_cout("[你突然聽見不遠處傳來寶可夢的尖叫聲");
		my_cout("[你]：發生什麼事了？走，我們去看看！");
		my_cout("[皮卡丘]：皮卡皮卡");
		my_cout("[你]：這是...圈圈熊？他在搶奪其他寶可夢摘下來的樹果");
		my_cout("[突然有一道綠色的身影閃過，快速地向圈圈熊襲去]");
		my_cout("[你]：那是...？");
		my_cout("[神秘男聲]：那是摔跤鷹人");
		my_cout("[你]：請問您是...？");
		my_cout("[神秘男聲]：我是這座森林的管理員");
		my_cout("[你]：您認識這隻摔跤鷹人嗎？");
		my_cout("[管理員]：嗯，摔跤鷹人是這座森林的守護者，負責維護寶可夢之間的和平");
		my_cout("[就在說話的同時，摔跤鷹人已經把圈圈熊打得節節敗退]");
		my_cout("[你]：那是？");
		my_cout("[只見摔跤鷹人飛到一旁的樹上，擺出了一個帥氣的姿勢]");
		my_cout("[管理員]：那是摔跤鷹人的招牌動作，先擺出姿勢，再使出絕招：飛行重壓。但是...");
		my_cout("[在摔跤鷹人擺好姿勢的同時，圈圈熊已經準備好迎擊。在摔跤鷹人使出飛行重壓時快速閃到一旁，而摔跤鷹人撞到地面，一時重傷不起]");
		my_cout("[你]：摔跤鷹人！");
		my_cout("[圈圈熊趁此機會想對摔跤鷹人進行復仇。他搬起一塊大石想往倒在地上的摔跤鷹人砸去]");
		my_cout("[你]：住手！圈圈熊！");
		my_cout("[你即刻衝過去，擋在摔跤鷹人與圈圈熊之間]");
		my_cout("[你]：皮卡丘，用鐵尾把石頭破壞掉！");
		my_cout("[皮卡丘使出鐵尾]");
		my_cout("[圈圈熊]：圈圈 圈圈");
		my_cout("[你]：皮卡丘，再來一擊。十萬伏特！");
		my_cout("[皮卡丘使出十萬伏特，圈圈熊眼看局勢不利便逃跑了]");
		my_cout("[你]：摔跤鷹人，你沒事吧？");
		my_cout("[摔跤鷹人]：cholu");
		my_cout("[你]：摔跤鷹人，我很欣賞你喔！");
		my_cout("[摔跤鷹人]：cholu");
		my_cout("[你]：我是一名寶可夢訓練家，你想不想跟我一起去旅行呢");
		my_cout("[摔跤鷹人]：cho...lu...？");
		my_cout("[你]：我們來進行對戰吧！");
		my_cout("[摔跤鷹人望了一會兒你伸向他的手，搭上了你的手心]");
	}
	my_cout("\n     [battle v.s. 摔跤鷹人]");
	pokemon* assign[1] = { &Hawlucha };
	win_or_lose = whole_battle(1, 1, NULL, assign);
	if (win_or_lose == false) {
		cout << "再鍛鍊鍛鍊寶可夢吧！\n";
		Hawlucha.set_HP(Hawlucha.get_max_HP());
		main_menu();
		mission3_1();
	}
	if (missions[2][0].get_complete() == false) {
		use_my_pokemon_ball();
		Hawlucha.be_catched(true);
		my_cout("[你]：成功收服摔跤鷹人了了！");
		my_cout("[皮卡丘]：皮卡皮卡");
		my_cout("[你]：摔跤鷹人，出來吧！");
		my_cout("[摔跤鷹人]：cholu");
		my_cout("[你]：摔跤鷹人，以後多多指教囉！");
		my_cout("[摔跤鷹人]：cholu");
		my_cout("[你]：好的，繼續前往娑羅市囉！");
		my_cout("[皮卡丘]：皮卡皮卡");
		my_cout(".\n.\n.\nTo be continued...");
		my_cout("\n[主線3-1 森林之王 completed]");
		my_cout("[獲得獎勵：三明治*5，好傷藥*5]");
		player.get_consumable(5)->add_num(5); player.get_consumable(8)->add_num(5);
		cin.ignore();
		my_cout("[寶可夢經驗值上升]");
		minus_health();
		missions[2][0].set_complete(true);
		current_mission = &missions[2][1];
		confirm_land_conflict();
		main_menu();
	}
}
void mission3_2() {//誰能制霸空中？ 小箭雀與烈箭鷹
	enter_mission(2, 1);
	missions[2][1].set_start(true);
	cin.ignore();
	my_cout("[你]：這裡就是娑羅市了！");
	my_cout("[皮卡丘]：皮卡皮卡");
	my_cout("[你]：咦？那裡有好多鳥在飛...不對，是人！？");
	my_cout("[神秘女聲]：那裡是疾風峽谷。人們穿上裝備，就可以像飛行系寶可夢一樣在天上飛，還可以在空中指揮寶可夢作戰");
	my_cout("[你]：哇，太酷了吧！");
	my_cout("[神秘女聲]：你們也想試試嗎？");
	my_cout("[你]：可以嗎？");
	my_cout("[神秘女聲]：當然可以！你是初學者吧？");
	my_cout("[你]：是的！");
	my_cout("[神秘女聲]：那你可以先到旁邊的空中飛人訓練中心學習飛行的技巧");
	my_cout("[你]：好的！對了，請問你叫什麼名字呢？");
	my_cout("[神秘女聲]：我叫娜米，這孩子是烈箭鷹");
	my_cout("[你]：謝謝你，娜米！我是來自" + player.get_loc() + "的" + player.get_name() + "，請多多指教");
	my_cout("[娜米]：不客氣！那我們快進去吧！");
	my_cout("\n[空中飛人訓練中心內]");
	my_cout("[娜米]：如何？好玩嗎？");
	my_cout("[你]：太好玩了！我好像飛在天上一樣！");
	my_cout("[娜米]：嗯，你很有天分呢！有沒有興趣來場對戰呢？");
	my_cout("[你]：當然！小箭雀，出來吧");
	my_cout("[烈箭鷹看了一眼小箭雀便撇開了頭]");
	my_cout("[娜米]：不好意思，這孩子不想跟小箭雀對戰呢！你還有其他飛行的寶可夢嗎？");
	my_cout("[你]：欸！我是有摔跤鷹人，可是...");
	my_cout("[娜米]：如果摔跤鷹人贏了我的烈箭鷹，我就答應跟小箭雀對戰");
	my_cout("[你]：......好！摔跤鷹人，出來吧！");
	my_cout("\n     [battle v.s. 娜米]");
	pokemon* assign[1] = { &Nami_Talonflame };
	choose_one_pokemon = &Hawlucha;
	win_or_lose = whole_battle(1, 1, &Nami, assign);
	if (win_or_lose == false) {
		my_cout("[對戰由訓練家米娜獲勝]");
		my_cout("[你]：辛苦你了，摔跤鷹人");
		my_cout("[小箭雀]：yako yakoyako");
		my_cout("[你]：小箭雀，你想對戰嗎？");
		my_cout("[小箭雀]：yako");
		my_cout("[娜米]：欸，可是剛剛不是說好贏了才對戰？而且摔跤鷹人都輸了，小箭雀就別不自量力了吧！");
		my_cout("[你]：戰鬥這種事，不試試怎麼會知道結果？拜託你了");
		my_cout("[娜米]：......好吧，那就來一場吧！");
	}
	else {
		my_cout("[娜米]：你們贏了。照約定，我們要跟小箭雀比一場！");
	}
	my_cout("\n     [battle v.s. 娜米]");
	choose_one_pokemon = &Fletchling;
	win_or_lose = whole_battle(1, 1, &Nami, assign);
	my_cout("[你]：火箭雀，辛苦了");
	my_cout("[火箭雀]：yama");
	if (win_or_lose == false) {
		my_cout("[娜米]：雖然你們還是沒有贏，不過小箭雀在這場對戰中進化了，恭喜你呀，" + player.get_name());
		my_cout("[你]：謝謝你，娜米");
		my_cout("[娜米]：不客氣！我跟烈箭鷹也成長了許多");
		my_cout("[你]：今天真的很開心呢！");
		my_cout("[娜米]：我也是！下次要再來玩喔！我們下次也會贏的");
		my_cout("[你]：我們會更努力不輸給你們的！");
		my_cout("[娜米]：我會拭目以待！");
		my_cout("[你]：娜米，下次見囉！皮卡丘，火箭雀，我們走吧！");
		my_cout("[皮卡丘]：皮卡皮卡");
		my_cout("[火箭雀]：yama");
	}
	else {
		my_cout("[娜米]：哇，我真是被火箭雀嚇了一跳！火箭雀，恭喜你呀！");
		my_cout("[火箭雀]：yama");
		my_cout("[你]：謝謝你，娜米");
		my_cout("[娜米]：不客氣！我跟烈箭鷹也成長了許多");
		my_cout("[你]：今天真的很開心呢！");
		my_cout("[娜米]：我也是！下次要再來玩喔！我們會贏的");
		my_cout("[你]：嗯，我們也會努力不輸給你們的！");
		my_cout("[你]：皮卡丘，火箭雀，我們走吧！");
		my_cout("[皮卡丘]：皮卡皮卡");
		my_cout("[火箭雀]：yama");
	}
	my_cout(".\n.\n.\nTo be continued...");
	my_cout("\n[主線3-2 誰能制霸空中？ 小箭雀與烈箭鷹 completed]");
	my_cout("[獲得獎勵：銀莓果*5，好傷藥*5]");
	player.get_consumable(2)->add_num(5); player.get_consumable(8)->add_num(5);
	my_cout("[寶可夢經驗值上升]");
	minus_health();
	missions[2][1].set_complete(true);
	current_mission = &missions[2][2];
	confirm_land_conflict();
	main_menu();
}
void mission3_3() {//挑戰格鬥道館 mega路卡利歐
	enter_mission(2, 2);
	if (missions[2][2].get_start() == false) {
		missions[2][2].set_start(true);
		cin.ignore();
		my_cout("[你]：終於來到娑羅市了！");
		my_cout("[皮卡丘]：皮卡皮卡");
		my_cout("[你]：地圖上寫，格鬥道館的所在地精煉之塔在小島上，但這裡也沒有看見碼頭啊！要怎麼過去啊？");
		my_cout("[神秘女聲]：你們要去格鬥道館嗎？");
		my_cout("[你]：是的！但這座小島看起來似乎沒有碼頭");
		my_cout("[神秘女聲]：再等等...大約十分鐘");
		my_cout("[你]：咦？十分鐘後就有人來接我們嗎？");
		my_cout("[神秘女聲]：你看就知道");
		my_cout("[十分鐘後，海水逐漸變淺，什至在某些地方露出地面，形成一條道路]");
		my_cout("[你]：哇！");
		my_cout("[神秘女聲]：走吧！太晚過去，走到一半會被淹沒的");
		my_cout("[你]：謝謝你！你也是要去挑戰道館的人嗎？");
		my_cout("[神秘女聲]：不是，我是那座島上的居民，我叫可爾妮");
		my_cout("[你]：謝謝你，可爾妮。我是來自" + player.get_loc() + "的" + player.get_name() + "，請多多指教");
		my_cout("[可爾妮]：這兒就到島上了。加油，挑戰者！");
		my_cout("\n[格鬥道館內]");
		my_cout("[你]：咦？那是路卡利歐的雕像！");
		my_cout("[皮卡丘]：皮卡皮卡");
		my_cout("[神秘女聲]：沒錯！路卡利歐是我們家族世世代代的夥伴，對我們有重大的意義");
		my_cout("[你]：可爾妮？");
		my_cout("[可爾妮]：這個地方記錄著路卡利歐與mega進化的歷史，我們也是卡洛斯地區最早開始mega進化的家族之一");
		my_cout("[可爾妮]：嗨" + player.get_name() + "，又見面了！");
		my_cout("[你]：你就是這裡的道館館主嗎？");
		my_cout("[可爾妮]：沒錯！重新向你自我介紹。我是格鬥道館的館主，可爾妮");
		my_cout("[你]：我是來挑戰道館的，請多多指教！");
		my_cout("[可爾妮]：好！那就讓我們開始吧！");
	}
	my_cout("\n     [battle v.s. 可爾妮]");
	pokemon* assign[3] = { &Mienfoo,&Machoke,&Lucario };
	win_or_lose = whole_battle(3, 3, &Korrina, assign);
	if (win_or_lose == false) {
		cout << "再鍛鍊鍛鍊寶可夢吧！\n";
		main_menu();
		mission3_3();
	}
	if (missions[2][2].get_complete() == false) {
		my_cout("[對戰裁判員]：本場對戰由挑戰者獲勝！");
		my_cout("[你]：太好了！");
		my_cout("[可爾妮]：辛苦了，路卡利歐");
		my_cout("[你]：謝謝你，可爾妮！");
		my_cout("[可爾妮]：這是你成功挑戰格鬥道館的證明：格鬥徽章");
		my_cout("[你獲得 格鬥徽章]");
		player.add_badge(badge("娑羅道館", 6));
		player.plus_badgenum();
		my_cout("[可爾妮]：之後的道館戰繼續加油喔！");
		my_cout("[你]：嗯！謝謝你，可爾妮！");
		my_cout("[你]：皮卡丘，我們前往下一個城市吧！");
		my_cout("[皮卡丘]：皮卡皮卡");
		my_cout(".\n.\n.\nTo be continued...");
		my_cout("\n[主線3-3 挑戰格鬥道館 mega路卡利歐 completed]");
		my_cout("[獲得獎勵：皮幣*500]");
		player.set_money(500);
		my_cout("[寶可夢經驗值上升]");
		minus_health();
		missions[2][2].set_complete(true);
		current_mission = &missions[2][3];
		confirm_land_conflict();
		main_menu();
	}
}
void mission3_4() {//河上飄來一名忍者？！ 三平與甲賀忍蛙
	enter_mission(2, 3);
	missions[2][3].set_start(true);
	cin.ignore();
	my_cout("[你]：呱呱泡蛙，出來吧！");
	my_cout("[呱呱泡蛙]：gerogero");
	my_cout("[你]：這裡正好有小溪，你去補充點水分吧");
	my_cout("[呱呱泡蛙]：gerogero");
	my_cout("[呱呱泡蛙]：gerogero gerogerogero");
	my_cout("[你]：怎麼了？呱呱泡蛙？");
	my_cout("[你]：咦，那是...？");
	my_cout("[河上突然漂來一名身穿忍者服的男子，你見狀趕緊將他救上了河");
	my_cout("[你]：你醒醒！");
	my_cout("[忍者]：啊...啊...");
	my_cout("[你]：你沒事吧？");
	my_cout("[忍者]：在下...在下...沒事了，謝謝你");
	my_cout("[你]：你還是再躺著休息一下吧");
	my_cout("[忍者]：好...謝謝你");
	my_cout("[你]：我是來自" + player.get_loc() + "的" + player.get_name());
	my_cout("[你]：你發生什麼事了？怎麼會跌到河中");
	my_cout("[忍者]：在下...在下是來自忍者村的忍者，在下叫三平，那孩子是甲賀忍蛙，是在下的夥伴");
	my_cout("[你]：忍者村？聽起來是好酷的地方");
	my_cout("[三平]：是的。忍者村村裡的人從小就會跟夥伴一起學習忍術。在下這次出來，是因為在下的師父才藏閣下給在下一件重要的任務，讓在下把一份忍術密笈送到某個宅邸");
	my_cout("[三平]：但是...");
	my_cout("[你]：但是？");
	my_cout("[神秘男聲]：找到你了");
	my_cout("[神秘男聲]：忍法，水遁之術");
	my_cout("[你]：咦？那是");
	my_cout("[三平]：那就是襲擊我們的人！");
	my_cout("[襲擊之人臉上戴著狡猾天狗的面具，從小溪另一頭走了出來");
	my_cout("[狡猾天狗假面]：正是，我要把密笈佔為己有。");
	my_cout("[狡猾天狗假面]：龜足巨鎧，使出貝殼刃");
	my_cout("[龜足巨鎧使出貝殼刃]");
	my_cout("[呱呱泡蛙]：gerogero");
	my_cout("[呱呱泡蛙使出泡沫]");
	my_cout("[三平]：好快");
	my_cout("[你]：呱呱泡蛙，使出水之波動！");
	my_cout("[呱呱泡蛙使出水之波動]");
	my_cout("[狡猾天狗假面]：哼，要來一戰嗎？");
	my_cout("[你]：奉陪到底！");
	my_cout("\n     [battle v.s. 狡猾天狗假面]");
	pokemon* assign[1] = { &Barbaracle };
	choose_one_pokemon = &Froakie;
	win_or_lose = whole_battle(1, 1, &Saizo, assign);
	if (win_or_lose == false) {
		my_cout("[三平]：在下先用忍術帶你們離開這兒吧");
		my_cout("[三平]：忍術，葉遁術");
		my_cout(".\n.\n.\nTo be continued...");
		my_cout("\n[主線3-4 河上飄來一名忍者？！ 三平與甲賀忍蛙 completed]");
		my_cout("[獲得獎勵：銀莓果*8，好傷藥*5]");
		player.get_consumable(2)->add_num(8); player.get_consumable(8)->add_num(5);
		//cin.ignore();
		my_cout("[寶可夢經驗值上升]");
		minus_health();
		missions[2][3].set_complete(true);
		current_mission = &missions[2][4];
		confirm_land_conflict();
		main_menu();
	}
}
void mission3_5() {//忍術對決 呱呱泡蛙與龜足巨鎧
	cout << "建議先將呱呱泡蛙的HP補滿以進行復仇之戰！\n";
	enter_mission(2, 4);
	missions[2][4].set_start(true);
	cin.ignore();
	my_cout("[你]：謝謝你，三平！");
	my_cout("[三平]：你們還是先走吧，不要再受在下牽連了");
	my_cout("[你]：不。剛剛被襲擊時，你的甲賀忍蛙中了龜足巨鎧的毒，已經沒辦法抵抗攻擊，我還是留下來幫你吧");
	my_cout("[三平]：謝謝你，" + player.get_name());
	my_cout("[你]：走這邊吧，我知道這兒有條小路，剛剛來時有看到");
	my_cout("[三平]：好，我們快走吧！");
	my_cout("[狡猾天狗假面]：你是逃不出我的手掌心的");
	my_cout("[你]：又是你！");
	my_cout("[狡猾天狗假面]：交出那份密笈吧！");
	my_cout("[你]：不可能！");
	my_cout("[狡猾天狗假面]：龜足巨鎧，貝殼刃");
	my_cout("[龜足巨鎧使出貝殼刃]");
	my_cout("[你]：呱呱泡蛙，要上囉");
	my_cout("[呱呱泡蛙]：gerogero");
	my_cout("\n     [battle v.s. 狡猾天狗假面]");
	pokemon* assign[1] = { &Barbaracle };
	choose_one_pokemon = &Froakie;
	win_or_lose = whole_battle(1, 1, &Saizo, assign);
	if (win_or_lose == true) {
		my_cout("[你]：呱頭蛙，你進化了呢！");
		my_cout("[呱頭蛙]：gual");
		my_cout("[你]：怎麼樣？狡猾天狗假面");
		my_cout("[狡猾天狗假面]：哼！");
		my_cout("[狡猾天狗假面]：忍術，葉遁術");
		my_cout("[狡猾天狗假面]：快去宅邸吧，三平！");
		my_cout("[三平]：謝謝你，" + player.get_name() + "，在下也得去宅邸了，就此別過");
		my_cout("[你]：不，這可能是陷阱。我陪你去吧");
		my_cout("[三平]：...好吧，謝謝你");
		my_cout("\n[宅邸外]");
		my_cout("[你]：這宅邸看起來好陰森...");
		my_cout("[三平]：打擾了，在下是三平，送來忍者村的密笈！");
		my_cout("[你]：有人嗎？");
		my_cout("[熟悉男聲]：哈哈哈哈哈哈哈哈");
		my_cout("[熟悉男聲]：真虧你們能夠來到這裡，做得好，三平");
		my_cout("[你]：狡猾天狗假面！？");
		my_cout("[狡猾天狗假面摘下面具]");
		my_cout("[三平]：師傅！");
		my_cout("[才藏]：你打開密笈看看吧！");
		my_cout("[三平]：上面什麼都沒寫？");
		my_cout("[才藏]：這是給你的考驗，我想知道在外修行的這段時間你究竟成長了多少");
		my_cout("[三平]：雖然是一張白紙，但密笈我確實送達了。我們完成了任務");
		my_cout("[才藏]：嗯。你和甲賀忍蛙共同扶持、成長的身影，我親眼目睹了。這件事我會確實向村里的長老彙報的。三平，繼續旅行，繼續成長吧！");
		my_cout("[三平]：謝謝您！");
		my_cout("[三平]：" + player.get_name() + "謝謝你！如果沒有你的幫忙，我不可能通過考驗");
		my_cout("[你]：不客氣！是吧，呱頭蛙！");
		my_cout("[呱頭蛙]：gual");
		my_cout("[三平]：我們就此別過，" + player.get_name() + "，我們有緣再見！");
		my_cout("[你]：再見，三平！");
		my_cout("[你]：呱頭蛙，皮卡丘，我們繼續前進吧！");
		my_cout("[呱頭蛙]：gual");
		my_cout("[皮卡丘]：皮卡皮卡");
		my_cout("\n[夕陽餘暉下映照著你與夥伴們的身影，宣示著你們還將繼續的旅程]");
		my_cout(".\n.\n.\nTo be continued...");
		my_cout("\n[主線3-5 忍術對決 呱呱泡蛙與龜足巨鎧 completed]");
		my_cout("[獲得獎勵：銀莓果*8，三明治*3]");
		player.get_consumable(2)->add_num(8); player.get_consumable(5)->add_num(3);
		my_cout("[寶可夢經驗值上升]");
		minus_health();
		missions[2][4].set_complete(true);
		current_mission = &missions[3][0];
		confirm_land_conflict();
		main_menu();
	}
}

void mission4_1() {//從天而降的龍？
	enter_mission(3, 0);
	missions[3][0].set_start(true);
	cin.ignore();
	my_cout("\n~~~~~主線第四章 開始~~~~~");
	my_cout("[你]：哇！前面有好大一座湖！");
	my_cout("[皮卡丘]：皮卡皮卡");
	my_cout("[你]：大家，都出來吧");
	my_cout("[呱頭蛙]：gual");
	my_cout("[摔跤鷹人]：cholu");
	my_cout("[火箭雀]：yama");
	my_cout("[你]：這裡好美，我們在這裡休息一下吧");
	my_cout("[火箭雀]：yama yamayama");
	my_cout("[你]：火箭雀，怎麼了？");
	my_cout("[突然，你的頭頂被某個濕濕軟軟的物體砸到]");
	my_cout("[火箭雀]：yama");
	my_cout("[你]：哇！是什麼？");
	my_cout("[你]：你是...黏黏寶？我記得在圖鑑上看過你，說你是......最弱的龍！");
	my_cout("[黏黏寶]：mae...mae...");
	my_cout("[你]：黏黏寶，你怎麼了？糟了，他太虛弱了");
	my_cout("[你]：呱頭蛙，對黏黏寶用水之波動");
	my_cout("[呱頭蛙]：gual");
	my_cout("[呱頭蛙使出水之波動]");
	my_cout("[你]：黏黏寶，你好點了嗎？");
	my_cout("[黏黏寶]：maemae maemae");
	my_cout("[你]：太好了！");
	my_cout("[武藏]：既然你誠心誠意地說「太好了」");
	my_cout("[小次郎]：我就大發慈悲的回答你");
	my_cout("[武藏]：為了防止世界被破壞");
	my_cout("[小次郎]：為了守護世界的和平");
	my_cout("[武藏]：貫徹愛與真實的邪惡");
	my_cout("[小次郎]：可愛又迷人的反派角色");
	my_cout("[武藏]：武藏！");
	my_cout("[小次郎]：小次郎！");
	my_cout("[武藏]：我們是穿梭在宇宙間的火箭隊二人組");
	my_cout("[小次郎]：白洞，白色的明天正等著我們");
	my_cout("[喵喵]：就是這樣喵~");
	my_cout("[你]：火箭隊？你們又出現了");
	my_cout("[武藏]：小鬼頭，乖乖把皮卡丘交出來吧！");
	my_cout("[你]：不可能！我不會把皮卡丘交給你們的！");
	my_cout("[你]：皮卡丘，鐵尾！");
	my_cout("[皮卡丘使出鐵尾]");
	my_cout("[小次郎]：栗烏賊，用煙幕！");
	my_cout("[栗烏賊使出煙幕]");
	my_cout("[你]：呱頭蛙，用居合斬！");
	my_cout("[呱頭蛙使出居合斬]");
	my_cout("[武藏]：南瓜精，用寄生種子！");
	my_cout("[南瓜精使出寄生種子]");
	my_cout("[你]：呱頭蛙，用水之波動！");
	my_cout("[呱頭蛙使出水之波動]");
	my_cout("[小次郎]：栗烏賊，用幻象光線！");
	my_cout("[栗烏賊使出幻象光線，擊中皮卡丘與呱頭蛙]");
	my_cout("[你]：皮卡丘，呱頭蛙，你們還好嗎？");
	my_cout("[皮卡丘對呱頭蛙使出鐵尾，呱頭蛙對皮卡丘使出居合斬]");
	my_cout("[你]：不！皮卡丘！呱頭蛙！");
	my_cout("[你]：他們中了幻象光線，精神受到影響了...");
	my_cout("[武藏]：南瓜精，用惡之波動！");
	my_cout("[南瓜精使出惡之波動]");
	my_cout("[你]：不！");
	my_cout("[你居身擋在呱頭蛙與皮卡丘前]");
	my_cout("[此時，黏黏寶出現，擋在火箭隊與你之間]");
	my_cout("[你]：黏黏寶！");
	my_cout("[黏黏寶使出克制，南瓜精與栗烏賊受到嚴重傷害]");
	my_cout("[武藏]：不可能！");
	my_cout("[此時，皮卡丘與呱頭蛙已經解除幻象光線的影響]");
	my_cout("[你]：皮卡丘，呱頭蛙，我們一起對抗他們！");
	my_cout("[皮卡丘]：皮卡皮卡");
	my_cout("[呱頭蛙]：gual");
	my_cout("[你]：皮卡丘，十萬伏特，呱頭蛙，燕返！");
	my_cout("[皮卡丘使出十萬伏特，呱頭蛙使出燕返]");
	my_cout("[火箭隊]：好討厭的感覺啊！");
	my_cout("\n[你]：黏黏寶，剛剛的克制很厲害喔！居然有那樣的威力，你一點也不弱呀！");
	my_cout("[皮卡丘]：皮卡皮卡");
	my_cout("[黏黏寶]：maemae");
	my_cout("[你]：你剛剛保護我們時，我感受到那份強烈的意志了");
	my_cout("[黏黏寶]：maemae");
	my_cout("[你]：你想不想跟我們一起去旅行呢？");
	my_cout("[黏黏寶]：maemae mae");
	my_cout("[你]：太好了！那麼，寶貝球");
	use_my_pokemon_ball();
	Goomy.be_catched(true);
	my_cout("[你]：成功收服黏黏寶了！");
	my_cout("[你]：我們繼續前進吧！目標是比翼道館");
	my_cout("[皮卡丘]：皮卡皮卡");
	my_cout("[呱頭蛙]：gual");
	my_cout("[黏黏寶]：maemae");
	my_cout(".\n.\n.\nTo be continued...");
	my_cout("\n[主線4-1 從天而降的龍？ completed]");
	my_cout("[獲得獎勵：銀莓果*8，好傷藥*5]");
	player.get_consumable(2)->add_num(8); player.get_consumable(8)->add_num(5);
	my_cout("[寶可夢經驗值上升]");
	minus_health();
	missions[3][0].set_complete(true);
	current_mission = &missions[3][1];
	confirm_land_conflict();
	main_menu();
}
void mission4_2() {//荒野決鬥 戰鬥吧，黏黏寶
	enter_mission(3, 1);
	missions[3][1].set_start(true);
	cin.ignore();
	my_cout("[你]：終於踏入比翼市了");
	my_cout("[皮卡丘]：皮卡皮卡");
	my_cout("[這時，你見到一群跳跳豬很有秩序地把數果搬進洞穴裡]");
	my_cout("[你]：看來這裡的寶可夢們也很團結呢");
	my_cout("[呱頭蛙]：gual gualgual gualgual");
	my_cout("[你]：...但他們的狀態看起來不太對...我們進洞穴去看一下狀況吧");
	my_cout("[黏黏寶]：maemae");
	my_cout("\n[洞穴內]");
	my_cout("[你]：那是...噗噗豬？是他在精神控制這些跳跳豬，讓他們為他搬運樹果");
	my_cout("[皮卡丘]：皮卡皮卡");
	my_cout("[你]：但我從來沒見過超能力系的招式可以一次控制這麼多寶可夢，真是奇怪啊...");
	my_cout("[武藏]：既然你誠心誠意的說了「真是奇怪啊！」");
	my_cout("[小次郎]：我就大發慈悲的回答你");
	my_cout("[武藏]：為了防止世界被破壞");
	my_cout("[小次郎]：為了守護世界的和平");
	my_cout("[武藏]：貫徹愛與真實的邪惡");
	my_cout("[小次郎]：可愛又迷人的反派角色");
	my_cout("[武藏]：武藏！");
	my_cout("[小次郎]：小次郎！");
	my_cout("[武藏]：我們是穿梭在宇宙間的火箭隊二人組");
	my_cout("[小次郎]：白洞，白色的明天正等著我們");
	my_cout("[喵喵]：就是這樣喵~");
	my_cout("[你]：火箭隊？又是你們？");
	my_cout("[武藏]：沒錯。小次郎、喵喵，我們趕緊把那幾袋樹果搬上外面的卡車吧！發大財囉！");
	my_cout("[你]：你們別想！");
	my_cout("[你]：呱頭蛙，居合斬！");
	my_cout("[呱頭蛙使出居合斬]");
	my_cout("[武藏]：哼！我們這次早就做好準備了");
	my_cout("[突然有鐵柵欄從洞穴頂端降下，你們就這樣被困在洞穴內部了]");
	my_cout("[小次郎]：阿咧咧，黏黏寶你這小傢伙怎麼沒被關到？");
	my_cout("[黏黏寶]：mae...mae...");
	my_cout("[武藏]：算了吧，他一個也掀不起什麼風浪。噗噗豬，你幫忙看管好他們喔！我們先繼續去搬樹果囉！");
	my_cout("[噗噗豬]：prinprin");
	my_cout("[你]：不，我們不能就這樣被關在這裡。呱頭蛙，對柵欄頂端使用居合斬，只要那附近的土壤鬆動，我們就能逃出去了");
	my_cout("[呱頭蛙]：gual");
	my_cout("[呱頭蛙使出居合斬]");
	my_cout("[噗噗豬對呱頭蛙使出暗影球]");
	my_cout("[你]：呱頭蛙！你還好嗎？");
	my_cout("[呱頭蛙]：gual");
	my_cout("[你]：太好了！");
	my_cout("[噗噗豬繼續對呱頭蛙使出暗影球]");
	my_cout("[黏黏寶用克制擋下了暗影球]");
	my_cout("[你]：黏黏寶，你想要戰鬥嗎？");
	my_cout("[黏黏寶]：maemae");
	my_cout("[你]：太好了！");
	my_cout("\n     [battle v.s. 噗噗豬]");
	pokemon* assign[1] = { &Grumpig };
	choose_one_pokemon = &Goomy;
	win_or_lose = whole_battle(1, 1, NULL, assign);
	if (win_or_lose == true) {
		my_cout("[你]：太好了！我們成功擊敗了噗噗豬！");
		my_cout("[你]：黏美兒，你太棒了！");
		my_cout("[黏美兒]：maelu");
		my_cout("[你]：呱頭蛙，趁此機會。對柵欄使出居合斬");
		my_cout("[呱頭蛙]：gual");
		my_cout("[呱頭蛙使出居合斬]");
		my_cout("[你]：我們趕緊出去吧！");
		my_cout("[皮卡丘]：皮卡皮卡");
		my_cout("[呱頭蛙]：gual");
		my_cout("[黏美兒]：maelu");
		my_cout("[火箭隊]：咦？你們怎麼逃出來了？");
		my_cout("[你]：我們不會讓你們得逞的！不多廢話，皮卡丘，十萬伏特！");
		my_cout("[皮卡丘使出十萬伏特]");
		my_cout("[火箭隊]：好討厭的感覺啊！");
		my_cout("[你]：跳跳豬的精神都恢復正常了！");
		my_cout("[噗噗豬]：prinprin");
		my_cout("[你]：噗噗豬，以後要跟跳跳豬們和平相處喔！不可以再欺負他們了！");
		my_cout("[噗噗豬]：prinprin");
		my_cout("[你]：那我們繼續前進吧！目標是比翼道館");
		my_cout("[皮卡丘]：皮卡皮卡");
		my_cout("[呱頭蛙]：gual");
		my_cout("[黏美兒]：maelu");
		my_cout(".\n.\n.\nTo be continued...");
		my_cout("\n[主線4-2 荒野決鬥 戰鬥吧，黏黏寶 completed]");
		my_cout("[獲得獎勵：銀莓果*8，好傷藥*5]");
		player.get_consumable(2)->add_num(8); player.get_consumable(8)->add_num(5);
		my_cout("[寶可夢經驗值上升]");
		minus_health();
		missions[3][1].set_complete(true);
		current_mission = &missions[3][2];
		confirm_land_conflict();
		main_menu();
	}
}
void mission4_3() {//挑戰比翼道館 細枝末節之處
	enter_mission(3, 2);
	if (missions[3][2].get_start() == false) {
		missions[3][2].set_start(true);
		cin.ignore();
		my_cout("[你]：比翼道館，我們來了！");
		my_cout("[皮卡丘]：皮卡皮卡");
		my_cout("[你]：我們進去吧！");
		my_cout("[皮卡丘]：皮卡皮卡");
		cout << "[你]：您好，我是來自" << player.get_loc() << "的" << player.get_name(); cin.ignore();
		my_cout("[道館館主]：歡迎來到比翼道館，我是比翼道館的館主，大家都叫我福爺。這是我的老夥伴，坐騎山羊");
		my_cout("[福爺]：你是來挑戰比翼道館的嗎？");
		my_cout("[你]：是的！我想要挑戰比翼道館，證明自己的實力！");
		my_cout("[福爺]：好！那麼...");
		my_cout("[你]：我們快點開始...");
		my_cout("[福爺]：趁此機會，你們先來幫我修剪花木吧！");
		my_cout("[你]：什麼？");
		my_cout("\n[花圃內]");
		my_cout("[你]：好想趕快開始道館戰啊！");
		my_cout("[皮卡丘]：皮卡皮卡");
		my_cout("[你一邊說，一邊大把大把的把雜草拔起來]");
		my_cout("[福爺]：喂，就算是雜草也不能隨便亂拔喔");
		my_cout("[福爺]：仔細看。雜草叢生處可能有新鮮的嫩芽；光被眼前的東西所迷惑，可能會看不到真正重要的東西喔！");
		my_cout("[福爺]：道館戰也是一樣的");
		my_cout("[你]：我明白了！");
		my_cout("[福爺]：那麼，差不多可以開始道館戰了！");
	}
	my_cout("\n     [battle v.s. 福爺]");
	my_cout("\n[對戰裁判員]：現在開始挑戰者" + player.get_name() + "與館主福爺的對戰。");
	my_cout("[對戰裁判員]：使用的寶可夢為三隻，若有一方的寶可夢全數失去戰鬥能力則對戰結束。只有挑戰者可進行寶可夢的替換。");
	my_cout("[福爺]：去吧，毽子棉！");
	pokemon* assign[3] = { &Jumpluff,&Weepinbell,&Gogoat };
	win_or_lose = whole_battle(3, 3, &Ramos, assign);
	if (win_or_lose == false) {
		cout << "再鍛鍊鍛鍊寶可夢吧！\n";
		main_menu();
		mission4_3();
	}
	if (missions[3][2].get_complete() == false) {
		my_cout("[對戰裁判員]：本場對戰由挑戰者獲勝！");
		my_cout("[福爺]：辛苦了，坐騎山羊！");
		my_cout("[福爺]：最後那招真棒啊");
		my_cout("[福爺]：這是你們的勝利證明，植物徽章！");
		my_cout("[獲得獎勵：植物徽章]");
		player.add_badge(badge("比翼道館", 4));
		player.plus_badgenum();
		my_cout("[你]：太好了！我們成功了！");
		my_cout("[你]：終於集齊四枚徽章了！我們回到那裡去吧！密阿雷市");
		my_cout("[皮卡丘]：皮卡皮卡");
		my_cout(".\n.\n.\nTo be continued...");
		my_cout("\n[主線4-3 挑戰比翼道館 細枝末節之處 completed]");
		my_cout("[獲得獎勵：皮幣*500]");
		player.set_money(500);
		my_cout("[寶可夢經驗值上升]");
		minus_health();
		missions[3][2].set_complete(true);
		current_mission = &missions[3][3];
		confirm_land_conflict();
		main_menu();
	}
}
void mission4_4() {//黏美兒會加油！
	enter_mission(3, 3);
	missions[3][3].set_start(true);
	cin.ignore();
	my_cout("[你]：昨晚跟希特隆通話，告訴他我們就要回密阿雷市的消息。他很期待呢！");
	my_cout("[皮卡丘]：皮卡皮卡");
	my_cout("[你]：他看起來已經準備很久了。皮卡丘，我們也來特訓吧！");
	my_cout("[皮卡丘]：皮卡皮卡");
	my_cout("[你]：還有你...黏美兒，出來吧！");
	my_cout("[黏美兒]：maelu");
	my_cout("[你]：我們一起來特訓吧！");
	my_cout("[皮卡丘]：皮卡皮卡");
	my_cout("[黏美兒]：maelu");
	my_cout("[突然，行動單輪機器人出現在你們面前，伸出來的兩隻機器手臂一把抓起皮卡丘]");
	my_cout("[你]：皮卡丘！這什麼東西呀？");
	my_cout("[武藏]：既然你誠心誠意的發問了！");
	my_cout("[小次郎]：我們就大發慈悲的回答你");
	my_cout("[武藏]：為了防止世界被破壞");
	my_cout("[小次郎]：為了守護世界的和平");
	my_cout("[武藏]：貫徹愛與真實的邪惡");
	my_cout("[小次郎]：可愛又迷人的反派角色");
	my_cout("[武藏]：武藏！");
	my_cout("[小次郎]：小次郎！");
	my_cout("[武藏]：我們是穿梭在宇宙間的火箭隊二人組");
	my_cout("[小次郎]：白洞，白色的明天正等著我們");
	my_cout("[喵喵]：就是這樣喵~");
	my_cout("[武藏]：姑且解釋一下。這是我們火箭隊的最新裝置：APC，負責感應皮卡丘體內的電流、自動捕捉！");
	my_cout("[小次郎]：小鬼頭，這次皮卡丘就歸我們啦！掰掰！");
	my_cout("[你]：不可能！我不會讓你們得逞的！黏美兒，對機器手臂使出龍之吐息");
	my_cout("[黏美兒]：maelu");
	my_cout("[黏美兒使出龍息，擊中機器手臂，皮卡丘被放了下來]");
	my_cout("[你]：快，往這邊跑");
	my_cout("[皮卡丘]：皮卡皮卡");
	my_cout("[黏美兒]：maelu");
	my_cout("[武藏]：可惡！南瓜精，使出惡之波動");
	my_cout("[南瓜精使出惡之波動]");
	my_cout("[你]：黏美兒，使出祈雨");
	my_cout("[黏美兒使出祈雨]");
	my_cout("[武藏]：南瓜精，再一次，惡之波動！");
	my_cout("[南瓜精使出惡之波動]");
	my_cout("[你]：黏美兒，皮卡丘，躲開！");
	my_cout("[黏美兒和皮卡丘躲開了南瓜精的攻擊，惡之波動正中APC，機器人爆炸，四周瞬間陷入火海，你與寶可夢、火箭隊都被火包圍]");
	my_cout("[喵喵]：怎麼會這樣？");
	my_cout("[你]：皮卡丘，小心左邊！");
	my_cout("[皮卡丘]：皮卡皮卡");
	my_cout("[你]：火勢太大了，這該怎麼辦...");
	my_cout("[黏美兒]：maelu maelumaelumaelu");
	my_cout("[黏美兒使出祈雨。同時，他周遭圍繞著白色的光");
	player.evolution(&Sliggoo);
	my_cout("[你]：這是...？");
	my_cout("[黏美兒進化成黏美露龍，使出的祈雨效果也比以往更顯著，火勢被順利撲滅了]");
	my_cout("[你]：太好了！黏美露龍，你進化了！");
	my_cout("[黏美露龍]：nelo");
	my_cout("[喵喵]：太好了，得救了");
	my_cout("[小次郎]：先不說這個。我們要不要順便抓一下黏美露龍啊？");
	my_cout("[武藏]：當然！南瓜精，暗影球！");
	my_cout("[小次郎]：栗烏賊，幻象光線！");
	my_cout("[南瓜精使出暗影球]");
	my_cout("[栗烏賊使出幻象光線]");
	my_cout("[你]：黏美露龍，小心！");
	my_cout("[黏美露龍使出龍之波動，擊中南瓜精與栗烏賊]");
	my_cout("[火箭隊]：好討厭的感覺啊！");
	my_cout("[你]：黏美露龍，你學會龍之波動了！真是太棒了");
	my_cout("[黏美露龍]：nelo");
	my_cout("[你]：好！黏美露龍也進化了。我們繼續前進吧！目標是密阿雷市");
	my_cout("[皮卡丘]：皮卡皮卡");
	my_cout("[黏美露龍]：nelo");
	my_cout("[就這樣，你們士氣高昂地前往密阿雷市。接下來還會發生很多故事，你們的旅程也還將繼續]");
	my_cout(".\n.\n.\nTo be continued...");
	my_cout("\n[主線4-4 黏美兒會加油！ completed]");
	my_cout("[獲得獎勵：三明治*5，銀莓果*10]");
	player.get_consumable(2)->add_num(10); player.get_consumable(5)->add_num(5);
	my_cout("[寶可夢經驗值上升]");
	minus_health();
	missions[3][3].set_complete(true);
	current_mission = &missions[4][0];
	confirm_land_conflict();
	main_menu();
}

void mission5_1() {//回到原點 挑戰密阿雷道館
	enter_mission(4, 0);
	if (missions[4][0].get_start() == false) {
		missions[4][0].set_start(true);
		cin.ignore();
		my_cout("\n~~~~~主線第五章 開始~~~~~");
		my_cout("[密阿雷道館門口，你深吸了一口氣]");
		my_cout("[你]：我是來自" + player.get_loc() + "的" + player.get_name() + "，我是來拿走密阿雷道館徽章的！");
		my_cout("[史特洛伊德]：是，這點很久以前就確認過了。請進吧！");
		my_cout("[希特隆]：" + player.get_name() + "，你們終於來了！");
		my_cout("[你]：久等了，希特隆，我們來戰鬥吧！");
		my_cout("[希特隆]：求之不得！");
	}
	my_cout("\n     [battle v.s. 希特隆]");
	my_cout("\n[史特洛伊德]：現在開始挑戰者" + player.get_name() + "與館主希特隆的對戰。");
	my_cout("[史特洛伊德]：使用的寶可夢為三隻，若有一方的寶可夢全數失去戰鬥能力則對戰結束。只有挑戰者可進行寶可夢的替換。");
	my_cout("[柚麗嘉]：哥哥！" + player.get_name() + "！加油！");
	my_cout("[希特隆]：平時與挑戰者對戰時不會派他，但今天是" + player.get_name() + "，所以，拜託了，掘掘兔！");
	pokemon* assign[3] = { &Bunnelby,&Heliolisk,&Luxray };
	win_or_lose = whole_battle(3, 3, &Clemont, assign);
	if (win_or_lose == false) {
		cout << "再鍛鍊鍛鍊寶可夢吧！\n";
		main_menu();
		mission5_1();
	}
	if (missions[4][0].get_complete() == false) {
		my_cout("[史特洛伊德]：本場對戰由挑戰者獲勝！");
		my_cout("[希特隆]：辛苦了，倫琴貓！");
		my_cout("[希特隆]：不愧是你，" + player.get_name());
		my_cout("[你]：謝謝你，希特隆！這場對戰真的很開心呢！");
		my_cout("[皮卡丘]：皮卡皮卡");
		my_cout("[希特隆]：多虧了你，我也很開心！");
		my_cout("[柚麗嘉]：哥哥，至今為止，今天的你最帥喔！");
		my_cout("[希特隆]：終於實現那天的約定了！這是你的勝利證明，雷電徽章！");
		my_cout("[獲得獎勵：雷電徽章]");
		player.add_badge(badge("密阿雷道館", 3));
		player.plus_badgenum();
		my_cout("[希特隆]：你想好接下來要去哪裡旅行了嗎？");
		my_cout("[你]：還沒耶...");
		my_cout("[希特隆]：不如接下來去香薰市吧！那裡是卡洛斯地區最古老的城市，有很多值得看的風景呢！");
		my_cout("[你]：好！我們就去香薰市吧！");
		my_cout("[皮卡丘]：皮卡皮卡");
		my_cout("[你]：對了希特隆，其實我之前就想問你...你要不要跟我一起去旅行呢？跟朋友一起去，旅途會很有趣的！");
		my_cout("[希特隆]：咦？我嗎...？但道館...");
		my_cout("[史特洛伊德]：我可以幫忙負責道館喔！您就安心地去吧！");
		my_cout("[柚麗嘉]：哥哥，去嘛！");
		my_cout("[希特隆]：柚麗嘉，是你自己也想去吧？");
		my_cout("[柚麗嘉]：唉呦哥哥，你怎麼就這樣一語道破？我才正想著你答應之後，拜託你帶上我呢！");
		my_cout("[眾人開心地笑了]");
		my_cout("[希特隆]：好！我就跟你一起去旅行吧，" + player.get_name());
		my_cout("[你]：太好了！目標香薰市，我們一起出發吧！");
		my_cout("[皮卡丘]：皮卡皮卡");
		my_cout(".\n.\n.\nTo be continued...");
		my_cout("\n[主線5-1 回到原點 挑戰密阿雷道館 completed]");
		my_cout("[獲得獎勵：皮幣*500]");
		player.set_money(500);
		my_cout("[寶可夢經驗值上升]");
		minus_health();
		missions[4][0].set_complete(true);
		current_mission = &missions[4][1];
		confirm_land_conflict();
		main_menu();
	}
}
void mission5_2() {//初遇翔太 三回合宿敵對戰
	enter_mission(4, 1);
	if (missions[4][1].get_start() == false) {
		missions[4][1].set_start(true);
		cin.ignore();
		my_cout("[你]：這裡就是香薰市！果然很美。街道上的建築都別有一番風味呢！");
		my_cout("[皮卡丘]：皮卡皮卡");
		my_cout("[希特隆]：對吧！");
		my_cout("[柚麗嘉]：哥哥" + player.get_name() + "，我們去那邊看看吧！");
		my_cout("[你]：那家店門前人好多啊！");
		my_cout("[希特隆]：那是卡洛斯地區最著名的服裝設計師——瑪秀的服裝店");
		my_cout("[你]：瑪秀？就是香薰是地道館館主嘛！");
		my_cout("[希特隆]：沒錯！");
		my_cout("[柚麗嘉]：我們可以進去看看嗎？");
		my_cout("[你]：當然可以！我們進去看看吧！");
		my_cout("[此時你見到旁邊有個人掉了本筆記本]");
		my_cout("[你]：欸！你的筆記本掉囉！");
		my_cout("[陌生男孩]：謝謝你！");
		my_cout("[陌生男孩]：欸你是...密阿雷道館的館主？");
		my_cout("[希特隆]：是的，你是...挑戰過密阿雷道館的...是叫翔太嗎？");
		my_cout("[翔太]：是的！沒想到您還記得我！");
		my_cout("[你]：翔太你好！我是來自" + player.get_loc() + "的" + player.get_name());
		my_cout("[翔太]：你好！我是來自豐原地區的翔太！");
		my_cout("[你]：翔太，那本筆記本是...？");
		my_cout("[翔太]：這是我一直在寫的寶可夢對戰筆記！我在與別人對戰後學到的東西都寫在裡面");
		my_cout("[你]：哇！");
		my_cout("[翔太]：" + player.get_name() + "你也是訓練家嗎？");
		my_cout("[你]：是的！我們要不要來場對戰？");
		my_cout("[翔太]：好啊！請多多指教！");
	}
	my_cout("\n     [battle v.s. 翔太]");
	my_cout("\n[翔太]：首先是你，寶貝龍，上吧！");
	pokemon* assign[3] = { &Bagon,&Slurpuff,&Treecko };
	win_or_lose = whole_battle(3, 3, &Sawyer, assign);
	if (win_or_lose == false) {
		cout << "再鍛鍊鍛鍊寶可夢吧！\n";
		main_menu();
		mission5_2();
	}
	if (missions[4][1].get_complete() == false) {
		my_cout("[翔太]：辛苦了，木守宮！");
		my_cout("[翔太]：謝謝你，" + player.get_name() + "，這場對戰中我學到很多！");
		my_cout("[你]：我也是！你的寶可夢們都很頑強呢！");
		my_cout("[翔太]：你來到薰香市，是為了挑戰薰香道館嗎？");
		my_cout("[你]：是的！翔太你挑戰過了嗎？");
		my_cout("[翔太]：嗯！但我沒有拿到徽章...");
		my_cout("[你]：欸！瑪秀小姐那麼強嗎？");
		my_cout("[翔太]：嗯！我還需要多鍛鍊呢！但你一定可以的！");
		my_cout("[你]：謝謝你！我們一起加油吧！");
		my_cout("[翔太]：好！祝你好運！");
		my_cout(".\n.\n.\nTo be continued...");
		my_cout("\n[主線5-2 初遇翔太 三回合宿敵對戰 completed]");
		my_cout("[獲得獎勵：好傷藥*10，銀莓果*5]");
		player.get_consumable(2)->add_num(5); player.get_consumable(8)->add_num(10);
		my_cout("[寶可夢經驗值上升]");
		minus_health();
		missions[4][1].set_complete(true);
		current_mission = &missions[4][2];
		confirm_land_conflict();
		main_menu();
	}
}
void mission5_3() {//挑戰香薰道館 美麗妖精的陷阱
	enter_mission(4, 2);
	if (missions[4][2].get_start() == false) {
		missions[4][2].set_start(true);
		cin.ignore();
		my_cout("[希特隆]：準備好了嗎？");
		my_cout("[你]：...還是有些緊張呢");
		my_cout("[希特隆]：你一定可以的。");
		my_cout("[你]：嗯。我們進去吧！");
		my_cout("[香薰道館裡一樣維持著香薰市的建築風格，令人不由得驚嘆]");
		my_cout("[你]：從沒見過蓋得這麼...精緻的道館");
		my_cout("[瑪秀]：歡迎來到香薰道館，我是香薰道館的館主，瑪秀。");
		my_cout("[你]：您好，我是來自" + player.get_loc() + "的" + player.get_name());
		my_cout("[瑪秀]：我知道你是來挑戰我的，對吧？手上有幾個徽章呢？");
		my_cout("[你]：我有五枚徽章！現在準備來拿下第六個");
		my_cout("[瑪秀]：有氣勢是好事，但我也不能那麼輕易就把徽章交給你呢！");
		my_cout("[你]：我不會輸的，瑪秀小姐！");
		my_cout("[瑪秀]：那麼，開始吧！");
	}
	my_cout("\n     [battle v.s. 瑪秀]");
	my_cout("\n[對戰裁判員]：現在開始挑戰者" + player.get_name() + "與館主瑪秀的對戰。");
	my_cout("[對戰裁判員]：使用的寶可夢為兩隻，若有一方的寶可夢全數失去戰鬥能力則對戰結束。只有挑戰者可進行寶可夢的替換。");
	my_cout("[瑪秀]：先從我開始");
	my_cout("[瑪秀]：去吧！仙子伊布！");
	pokemon* assign[2] = { &Sylveon,&Spritzee };
	win_or_lose = whole_battle(2, 2, &Valerie, assign);
	if (win_or_lose == false) {
		cout << "再鍛鍊鍛鍊寶可夢吧！\n";
		main_menu();
		mission5_3();
	}
	if (missions[4][2].get_complete() == false) {
		my_cout("[對戰裁判員]：本場對戰由挑戰者獲勝！");
		my_cout("[瑪秀]：辛苦了，粉香香！");
		my_cout("[柚麗嘉]：恭喜你！" + player.get_name());
		my_cout("[希特隆]：這場對戰真的很精彩！");
		my_cout("[你]：謝謝你們！");
		my_cout("[瑪秀]：你知道嗎？與寶可夢心靈相通這種事，只有在對戰被逼入絕境時才偶爾會發生。但那又是怎麼辦到的呢？真的很神奇，對吧！");
		my_cout("[你]：嗯...雖然不太清楚，但總覺得心中知道答案！");
		my_cout("[瑪秀]：原來如此");
		my_cout("[瑪秀]：這是你的勝利證明，妖精徽章！");
		my_cout("[你]：謝謝您，瑪秀小姐！");
		my_cout("[獲得獎勵：妖精徽章]");
		player.add_badge(badge("香薰道館", 17));
		player.plus_badgenum();
		my_cout("[瑪秀]：加油，挑戰者！快去集齊八枚徽章吧！");
		my_cout("[你]：嗯！我會的！");
		my_cout("[皮卡丘]：皮卡皮卡");
		my_cout("[你]：希特隆，接下來我們要去那兒呢？");
		my_cout("[希特隆]：嗯...我們沿著路到百刻市去吧！那裡有超大的日晷，來卡洛斯地區一定要去看的！");
		my_cout("[瑪秀]：百刻道館的館主午時花女士可不好對付喔！");
		my_cout("[你]：好！我會加油的！");
		my_cout("[皮卡丘]：皮卡皮卡");
		my_cout(".\n.\n.\nTo be continued...");
		my_cout("\n[主線5-3 挑戰香薰道館 美麗妖精的陷阱 completed]");
		my_cout("[獲得獎勵：皮幣*500]");
		player.set_money(500);
		my_cout("[寶可夢經驗值上升]");
		minus_health();
		missions[4][2].set_complete(true);
		current_mission = &missions[4][3];
		confirm_land_conflict();
		main_menu();
	}
}
void mission5_4() {//蛋裡的baby
	enter_mission(4, 3);
	missions[4][3].set_start(true);
	cin.ignore();
	my_cout("[摔跤鷹人]：cholucholu");
	my_cout("[你]：欸？摔跤鷹人，這是...？");
	my_cout("[希特隆]：摔跤鷹人找了顆蛋給你呢！" + player.get_name());
	my_cout("[摔跤鷹人]：cholucholu");
	my_cout("[你]：欸...欸欸，希特隆，這顆蛋在發光");
	my_cout("[希特隆]：那是快孵化了！" + player.get_name() + "，抱著它幫它加熱會比較容易孵化");
	my_cout("[你]：好！火箭雀，出來吧！");
	my_cout("[火箭雀]：yama");
	my_cout("[你]：火箭雀，用體溫幫忙加熱這顆蛋！");
	my_cout("[火箭雀]：yama");
	my_cout("[希特隆]：對耶！因為火箭雀是火系，體溫相較於其他寶可夢會更高一些");
	my_cout("[柚麗嘉]：我也來！");
	my_cout("[眾人抱了蛋一會兒，蛋便順利孵化了");
	my_cout("[希特隆]：這是嗡蝠！");
	my_cout("[柚麗嘉]：他睜開眼睛了！");
	my_cout("[你]：哈囉，嗡蝠");
	my_cout("[皮卡丘]：皮卡皮卡");
	my_cout("[你]：我叫" + player.get_name() + "，這是皮卡丘");
	my_cout("[希特隆]：我是希特隆！");
	my_cout("[柚麗嘉]：我是柚麗嘉！");
	my_cout("[嗡蝠]：gu...gugu...guaaaaaaaaaa");
	my_cout("[希特隆]：快摀住耳朵...這是嗡蝠的超音波");
	my_cout("[柚麗嘉]：嗡蝠，別哭了！");
	my_cout("[嗡蝠]：guaaaaaaaaaa");
	my_cout("[你]：嗡蝠，沒事，不哭囉！");
	my_cout("[嗡蝠]：gu...gugu");
	my_cout("[柚麗嘉]：他很聽" + player.get_name() + "的話呢");
	my_cout("[希特隆]：大概是把" + player.get_name() + "當成父母了吧！");
	my_cout("[你]：嗡蝠，你餓了嗎？吃點樹果吧！");
	my_cout("[嗡蝠]：gugu");
	my_cout("[你]：再喝點水吧！");
	my_cout("[嗡蝠]：gugu");
	my_cout("[嗡蝠]：gugu gugugugu");
	my_cout("[嗡蝠往前走了幾步，拍拍翅膀]");
	my_cout("[你]：他是想飛嗎？");
	my_cout("[嗡蝠順利在空中振了五次翅，卻不小心摔了下來]");
	my_cout("[嗡蝠]：gu...gugu...guaaaaaaaaaa");
	my_cout("[柚麗嘉]：啊啊啊！又哭了");
	my_cout("[你]：嗡蝠，沒事，不哭囉！");
	my_cout("[嗡蝠]：gugugu");
	my_cout("[你]：在挑戰一次吧！");
	my_cout("[嗡蝠在空中振了幾次翅，卻又摔了下來，此時，你撲到地上接住了他]");
	my_cout("[嗡蝠]：gugu");
	my_cout("[你]：看吧！沒事的");
	my_cout("[柚麗嘉]：因為是小嬰兒的關係所以不能飛嗎？");
	my_cout("[希特隆]：一般來說剛出生就能飛的");
	my_cout("[你]：肯定是需要一些訣竅吧！就像騎腳踏車那樣");
	my_cout("[你]：火箭雀、摔跤鷹人，你們可以教教嗡蝠嗎？");
	my_cout("[火箭雀]：yama");
	my_cout("[摔跤鷹人]：cholucholu cholucholucholucholu");
	my_cout("[你]：摔跤鷹人，你有什麼想法嗎？");
	my_cout("[摔跤鷹人]：cholucholu");
	my_cout("[你們跟著摔跤鷹人來到一片開闊的山丘]");
	my_cout("[希特隆]：山丘上風大，確實很適合練習乘風飛翔");
	my_cout("[摔跤鷹人]：cholucholu");
	my_cout("[嗡蝠]：gugugu");
	my_cout("[嗡蝠跟著摔跤鷹人一起飛了起來]");
	my_cout("[你]：做得好，嗡蝠！");
	my_cout("[嗡蝠]：guguguaaa");
	my_cout("[事情卻沒有那麼順利。嗡蝠又一個重心不穩，即將摔落地面]");
	my_cout("[你]：嗡蝠！");
	my_cout("[火箭雀]：yama yamayama");
	my_cout("[火箭雀立刻衝過去接住了嗡蝠]");
	my_cout("[你]：火箭雀，謝謝你！");
	my_cout("[嗡蝠]：gugu");
	my_cout("[你]：嗡蝠，我們在多練習幾次吧！你一定可以飛起來的！");
	my_cout("[嗡蝠]：gugu");
	my_cout("[嗡蝠拍拍翅膀，準備起飛]");
	my_cout("[你]：沒錯，嗡蝠，就是這樣！");
	my_cout("[摔跤鷹人]：cholu");
	my_cout("[火箭雀]：yama yamayama yamayama");
	my_cout("[突然有一張大網從天外飛來]");
	my_cout("[你]：嗡蝠、摔跤鷹人，小心！");
	my_cout("[摔跤鷹人]：cholu");
	my_cout("[你]：你們還好嗎？");
	my_cout("[摔跤鷹人]：cholu");
	my_cout("[嗡蝠]：gugu");
	my_cout("[你]：是誰做出這種事？");
	my_cout("[武藏]：既然你誠心誠意地問了「是誰做出這種事」？");
	my_cout("[小次郎]：我就大發慈悲地告訴你");
	my_cout("[武藏]：為了防止世界被破壞");
	my_cout("[小次郎]：為了守護世界的和平");
	my_cout("[武藏]：貫徹愛與真實的邪惡");
	my_cout("[小次郎]：可愛又迷人的反派角色");
	my_cout("[武藏]：武藏！");
	my_cout("[小次郎]：小次郎！");
	my_cout("[武藏]：我們是穿梭在宇宙間的火箭隊二人組");
	my_cout("[小次郎]：白洞，白色的明天正等著我們");
	my_cout("[喵喵]：就是這樣喵~");
	my_cout("[你]：火箭隊！又是你們！");
	my_cout("[武藏]：我們要把這隻嗡蝠抓走，讓他成為我們的寶可夢");
	my_cout("[你]：不行！嗡蝠是我們的朋友！");
	my_cout("[武藏]：誰理你呀！南瓜精，暗影球！");
	my_cout("[南瓜精使出暗影球]");
	my_cout("[你]：摔跤鷹人，用飛膝踢！");
	my_cout("[摔跤鷹人使出飛膝踢]");
	my_cout("[小次郎]：栗烏賊，用煙幕");
	my_cout("[栗烏賊使出煙幕]");
	my_cout("[你]：火箭雀，用旋風刀！");
	my_cout("[火箭雀使出旋風刀]");
	my_cout("[你]：最後一擊，皮卡丘！十萬伏特");
	my_cout("[皮卡丘使出十萬伏特]");
	my_cout("[武藏]：連那隻嗡蝠都不會飛，我們卻會飛呢！");
	my_cout("[火箭隊]：好討厭的感覺啊！");
	my_cout("[柚麗嘉]：哥哥、" + player.get_name() + "，你們看！");
	my_cout("[希特隆]：嗡蝠！他飛起來了！");
	my_cout("[嗡蝠]：gugu");
	my_cout("[你]：嗡蝠，恭喜你！");
	my_cout("[摔跤鷹人]：cholu");
	my_cout("[火箭雀]：yamayama");
	my_cout("[你]：今天處理完火箭隊了！我們也該繼續前進了");
	my_cout("[皮卡丘]：皮卡皮卡");
	my_cout("[你]：嗡蝠，你要怎麼辦呢？");
	my_cout("[嗡蝠]：gugu");
	my_cout("[你]：我的意思是，你要跟我們一起去旅行嗎？");
	my_cout("[嗡蝠]：gugu gugugugu");
	my_cout("[你]：太好了！寶貝球");
	use_my_pokemon_ball();
	Noibat.be_catched(true);
	my_cout("[你]：成功收服嗡蝠了！");
	my_cout("[希特隆]：時間不早了，我們快走吧！");
	my_cout("[柚麗嘉]：哥哥，今天好累呀，我們可以去住寶可夢中心嗎？");
	my_cout("[希特隆]：咦？你不是早上才說今天還想野營嗎？");
	my_cout("[今日就在眾人的笑聲之中畫下句點，而你與夥伴們的旅程還將繼續]");
	my_cout(".\n.\n.\nTo be continued...");
	my_cout("\n[主線5-4 蛋裡的baby completed]");
	my_cout("[獲得獎勵：銀莓果*10]");
	player.get_consumable(2)->add_num(10);
	my_cout("[寶可夢經驗值上升]");
	minus_health();
	missions[4][3].set_complete(true);
	current_mission = &missions[5][0];
	confirm_land_conflict();
	main_menu();
}

void mission6_1() {//千年一遇的赤紅傳奇 火箭雀vs火焰鳥
	enter_mission(5, 0);
	missions[5][0].set_start(true);
	cin.ignore();
	my_cout("\n~~~~~主線第六章 開始~~~~~");
	my_cout("[希特隆]：這裡是百刻市著名的景點，除了日晷以外也必來的地方：阿多爾山的火山地形");
	my_cout("[你]：這裡的景色真的很美！");
	my_cout("[柚麗嘉]：不只如此呢，" + player.get_name() + "，這裡最知名的是傳說中的寶可夢：火焰鳥。有許多曾經在這裡目擊過火焰鳥的說法。");
	my_cout("[你]：火焰鳥？希望我們也有機會能遇到呢");
	my_cout("[希特隆]：我們繼續往前走，到火山口附近等等看吧！");
	my_cout("[你]：好！");
	my_cout("\n[火山口]");
	my_cout("[你]：這裡就是火山口了！");
	my_cout("[柚麗嘉]：真的很壯觀呢！就算看不到火焰鳥，也很值得上來一趟");
	my_cout("[突然，一個玻璃籠子朝皮卡丘飛了過來]");
	my_cout("[你]：皮卡丘！");
	my_cout("[希特隆]：是火箭隊！");
	my_cout("[武藏]：既然你誠心誠意地說了「火箭隊」！");
	my_cout("[小次郎]：我就大發慈悲地回答你「沒錯」！");
	my_cout("[武藏]：為了防止世界被破壞");
	my_cout("[小次郎]：為了守護世界的和平");
	my_cout("[武藏]：貫徹愛與真實的邪惡");
	my_cout("[小次郎]：可愛又迷人的反派角色");
	my_cout("[武藏]：武藏！");
	my_cout("[小次郎]：小次郎！");
	my_cout("[武藏]：我們是穿梭在宇宙間的火箭隊二人組");
	my_cout("[小次郎]：白洞，白色的明天正等著我們");
	my_cout("[喵喵]：就是這樣喵~");
	my_cout("[你]：火箭隊！又是你們！把我的皮卡丘還來");
	my_cout("[武藏]：你覺得我們會聽你的嗎？");
	my_cout("[你]：那就沒辦法了。火箭雀，出來吧！");
	my_cout("[火箭雀]：yama");
	my_cout("[你]：火箭雀，旋風刀！");
	my_cout("[火箭雀使出旋風刀]");
	my_cout("[小次郎]：栗烏賊，用幻象光線");
	my_cout("[栗烏賊使出幻象光線]");
	my_cout("[武藏]：南瓜精，暗影球！");
	my_cout("[南瓜精使出暗影球]");
	my_cout("[火箭雀一一躲過]");
	my_cout("[你]：火箭雀，蓄能焰襲！");
	my_cout("[火箭雀使出蓄能焰襲]");
	my_cout("[火箭雀的蓄能焰襲擊中了籠子，皮卡丘成功逃出]");
	my_cout("[你]：皮卡丘，你沒事吧！");
	my_cout("[皮卡丘]：皮卡皮卡");
	my_cout("[你]：那就用鐵尾！");
	my_cout("[皮卡丘使出鐵尾]");
	my_cout("[武藏]：南瓜精，惡之波動！");
	my_cout("[小次郎]：栗烏賊，用幻象光線");
	my_cout("[南瓜精使出惡之波動]");
	my_cout("[栗烏賊使出幻象光線]");
	my_cout("[你]：皮卡丘、火箭雀，躲開");
	my_cout("[皮卡丘、火箭雀一一躲過攻擊，攻擊擊落了一塊岩石，掉進火山口中]");
	my_cout("[你]：火箭雀再一次攻擊囉！");
	my_cout("[火箭雀]：yamayama yamayamayama");
	my_cout("[你]：火箭雀，怎麼了？");
	my_cout("[希特隆]：那是...那是火焰鳥！確實，我曾聽過火焰鳥會躲在岩漿裡頭休息這種說法");
	my_cout("[喵喵]：居然是火焰鳥！改變計畫，放棄皮卡丘，捕捉火焰鳥！");
	my_cout("[武藏]：南瓜精，惡之波動！");
	my_cout("[小次郎]：栗烏賊，用幻象光線");
	my_cout("[南瓜精使出惡之波動]");
	my_cout("[栗烏賊使出幻象光線]");
	my_cout("[火焰鳥使出噴射火焰]");
	my_cout("[小次郎]：不愧是神獸的噴射火焰...");
	my_cout("[火箭隊]：好討厭的感覺啊！");
	my_cout("[火焰鳥對著你們使出噴射火焰]");
	my_cout("[你]：皮卡丘、火箭雀，躲開！");
	my_cout("[柚麗嘉]：火焰鳥為甚麼要攻擊我們？");
	my_cout("[希特隆]：大概，他以為我們跟火箭隊是一夥的吧");
	my_cout("[你]：火焰鳥，等等，我們不是...");
	my_cout("[火焰鳥使出噴射火焰]");
	my_cout("[你]：沒辦法了。呱頭蛙，出來吧！");
	my_cout("[呱頭蛙]：gual");
	my_cout("[你]：呱頭蛙，水之波動！");
	my_cout("[呱頭蛙使出水之波動，但水在火焰鳥面前蒸發了]");
	my_cout("[希特隆]：怎麼會這樣...");
	my_cout("[你]：既然水沒辦法，那就只能用火了。火箭雀，蓄能焰襲");
	my_cout("[火箭雀使出蓄能焰襲]");
	my_cout("[火焰鳥使出噴射火焰]");
	my_cout("\n     [battle v.s. 火焰鳥]");
	pokemon* assign[1] = { &Moltres };
	choose_one_pokemon = &Fletchinder;
	win_or_lose = whole_battle(1, 1, NULL, assign);
	if (win_or_lose == false) {
		my_cout("[烈箭鷹受到重擊，跌入火山口中]");
		my_cout("[你]：烈箭鷹！");
		my_cout("[你為了救烈箭鷹，也往火山口跳下去]");
		my_cout("[希特隆]：" + player.get_name() + "！");
		my_cout("[呱頭蛙使出泡沫，泡沫黏成一長串，把你跟烈箭鷹捆住]");
		my_cout("[希特隆]：呱頭蛙，快把他們拉上來！");
		my_cout("[呱頭蛙]：gual");
		my_cout("[你]：謝謝你，呱頭蛙！");
		my_cout("[希特隆]：你沒事吧？");
		my_cout("[你]：嗯，謝謝你，希特隆！");
		my_cout("[皮卡丘]：皮卡皮卡");
		my_cout("[你]：皮卡丘，讓你擔心了！");
		my_cout("[火焰鳥振翅離去]");
		my_cout("[希特隆]：他大概知道我們不是他的敵人了吧！");
		my_cout("[你]：話說回來，我們居然真的看到火焰鳥了！");
		my_cout("[柚麗嘉]：是呢！這次的旅程真的很刺激！");
		my_cout("[柚麗嘉]：但是，哥哥，我累了");
		my_cout("[希特隆]：好~我們趕快進百刻市市區吧");
		my_cout("[你]：走吧！");
		my_cout(".\n.\n.\nTo be continued...");
		my_cout("\n[主線6-1 千年一遇的赤紅傳奇 火箭雀vs火焰鳥 completed]");
		my_cout("[獲得獎勵：三明治*5，銀莓果*10]");
		player.get_consumable(2)->add_num(10); player.get_consumable(5)->add_num(5);
		my_cout("[寶可夢經驗值上升]");
		minus_health();
		missions[5][0].set_complete(true);
		current_mission = &missions[5][1];
		confirm_land_conflict();
		main_menu();
	}

}
void mission6_2() {//挑戰百刻道館 精神力量的對決
	enter_mission(5, 1);
	if (missions[5][1].get_start() == false) {
		missions[5][1].set_start(true);
		cin.ignore();
		my_cout("[你]：哇！那個閃閃發亮的東西就是日晷嗎？");
		my_cout("[希特隆]：對呀！那就是百刻市的日晷，卡洛斯七大奇景之一。我們走近一點看看吧！");
		my_cout("[你]：好！");
		my_cout("[柚麗嘉]：那裡似乎有人在做研究呢！");
		my_cout("[你]：欸！是普拉塔諾博士！");
		my_cout("[皮卡丘]：皮卡皮卡");
		my_cout("[普拉塔諾博士]：哦！是你們啊！" + player.get_name() + "、希特隆、柚麗嘉");
		my_cout("[你]：博士！好久不見！你們是在進行對日晷的研究嗎？");
		my_cout("[普拉塔諾博士]：嗯！我們最近發現，日晷放射出的能量與mega進化的能量有些相似");
		my_cout("[你]：欸？！");
		my_cout("[普拉塔諾博士]：午時花女士，您好");
		my_cout("[普拉塔諾博士突然向你身後開口。你轉過身順著博士的視線一看，居然看到有人浮在半空中]");
		my_cout("[你]：那是...超能力？");
		my_cout("[午時花]：歡迎遠方的朋友蒞臨。爾等在此專心研究，吾等會盡地主之誼，若有需要可隨時至百刻道館告知吾等");
		my_cout("[普拉塔諾博士]：謝謝您，午時花女士");
		my_cout("[午時花]：那隻呱頭蛙...是...");
		my_cout("[你]：您是說我的呱頭蛙嗎？");
		my_cout("[午時花突然雙眼瞪大，一會兒後才和緩過來]");
		my_cout("[午時花]：方才吾見到了那隻呱頭蛙的未來，詳情於道館告知");
		my_cout("\n[百刻道館]");
		my_cout("[柚麗嘉]：能看到未來，感覺好酷啊！我也想看到我的未來，比如能不能成為訓練家之類的");
		my_cout("[午時花的弟子]：未來不是隨意就能看到的。午時花大人是遵循星宿的指引才看到了這世界某部分的未來。");
		my_cout("[你]：午時花女士，您所說的呱頭蛙的未來究竟是什麼呢？");
		my_cout("[午時花]：孩子，吾知曉了你的呱頭蛙是一隻從過去到未來都命運多舛的寶可夢。他與其他的寶可夢不同");
		my_cout("[你]：不同？那是什麼意思？");
		my_cout("[午時花]：那是剛出生的呱呱泡蛙。心無旁鶩，日鍛月煉；誌存高遠，孤高自持。卻也因此與其他寶可夢格格不入，紛爭不斷。");
		my_cout("[午時花]：終於，某日，他從人類身上領悟到了：單憑自身孤掌難鳴，唯有與訓練家合作，力量才會倍增的道理。是人類所傳達的無聲勝有聲的情感改變了呱呱泡蛙啊。");
		my_cout("[午時花]：此後，呱呱泡蛙培養出了選擇訓練家的眼光。他的標準只有一個：那就是對方值不值得自己賭上一切。他的標準高，所以總是不滿足");
		my_cout("[午時花]：與新人訓練家配合，一開始都不會順利，人人都有對第一次經歷的事感到迷茫的時候。但呱呱泡蛙在意的不是這些，他所追求的是更深層的東西。");
		my_cout("[午時花]：吾欲將其稱作為，愛");
		my_cout("[普拉塔諾博士]：沒想到原來是愛啊");
		my_cout("[你]：原來是你選擇了我啊，呱頭蛙");
		my_cout("[呱頭蛙]：gual");
		my_cout("[你]：我們一樣渴望變強！一起變強吧！首先目標是聯盟優勝，接著是寶可夢大師！");
		my_cout("[呱頭蛙]：gual");
		my_cout("[普拉塔諾博士]：午時花女士，那麼呱頭蛙的未來究竟是什麼呢？");
		my_cout("[午時花]：他會更進一步獲得力量");
		my_cout("[你]：這股力量是指進化成甲賀忍蛙嗎？");
		my_cout("[午時花]：這個，吾並不知曉");
		my_cout("[午時花]：但是，他的未來確實是誰都未曾一見的登峰造極之路。你們二人將會一起登頂吧。");
		my_cout("[普拉塔諾博士]：...難不成是mega進化？");
		my_cout("[眾人]：mega進化？");
		my_cout("[普拉塔諾博士]：不，但甲賀忍蛙從未有過mega進化的先例");
		my_cout("[希特隆]：那確實能算上是一個大事件呢！");
		my_cout("[你]：呱頭蛙，我們一起去見識這個未來吧！但首先...");
		my_cout("[呱頭蛙]：gual");
		my_cout("[你]：首先，我們要挑戰百刻道館，拿下第七個徽章！");
		my_cout("[呱頭蛙]：gual");
		my_cout("[你]：午時花女士，請馬上開始與我的道館戰吧！");
		my_cout("[午時花]：汝，名為？");
		my_cout("[你]：我是來自" + player.get_loc() + "的" + player.get_name() + "！");
		my_cout("[午時花]：吾接受挑戰。");
	}
	my_cout("\n     [battle v.s. 午時花]");
	my_cout("\n[對戰裁判員]：現在開始挑戰者" + player.get_name() + "與館主午時花的對戰。");
	my_cout("[對戰裁判員]：使用的寶可夢為兩隻，若有一方的寶可夢全數失去戰鬥能力則對戰結束。雙方不得進行寶可夢的替換。");
	my_cout("[午時花]：上吧！超能妙喵");
	pokemon* assign[2] = { &male_Meowstic,&female_Meowstic };
	win_or_lose = whole_battle(2, 2, &Olympia, assign);
	if (win_or_lose == false) {
		cout << "再鍛鍊鍛鍊寶可夢吧！\n";
		main_menu();
		mission6_2();
	}
	if (missions[5][1].get_complete() == false) {
		my_cout("[對戰裁判員]：本場對戰由挑戰者獲勝！");
		my_cout("[午時花]：超能妙喵，汝回應了吾之期望，戰鬥得很出色。休息吧");
		my_cout("[你]：謝謝您，午時花女士！");
		my_cout("[午時花]：最後一擊裡包含強烈的愛。汝與汝之寶可夢定能登上顛峰。但是這份愛，汝等要用心去對待");
		my_cout("[你]：是！");
		my_cout("[午時花]：吾授予汝戰勝百刻道館之證明。這是超能力徽章");
		my_cout("[獲得獎勵：超能力徽章]");
		player.add_badge(badge("百刻道館", 10));
		player.plus_badgenum();
		my_cout("[你]：謝謝您！");
		my_cout("[午時花]：吾期待汝之未來。至於呱頭蛙的未來...");
		my_cout("[午時花]：銘記於心，且待時機降臨即可。屆時汝將會感受到，寶可夢與人類之間新的可能性");
		my_cout("[你]：謝謝您，午時花女士！");
		my_cout("[希特隆]：恭喜你！現在只差最後一個徽章就能挑戰聯盟賽了！");
		my_cout("[你]：是阿！多虧你們陪我！");
		my_cout("[柚麗嘉]：哥哥，我們接下來要去那兒呢？");
		my_cout("[希特隆]：接下來我們要去映雪市吧！");
		my_cout("[你]：映雪市？這個城市光市名字聽起來就好美呀");
		my_cout("[希特隆]：是呀！現在這個季節去，應該可以看到雪喔！");
		my_cout("[你]：好！那我們趕快出發吧！");
		my_cout(".\n.\n.\nTo be continued...");
		my_cout("\n[主線6-2 挑戰百刻道館 精神力量的對決 completed]");
		my_cout("[獲得獎勵：皮幣*500]");
		player.set_money(500);
		my_cout("[寶可夢經驗值上升]");
		minus_health();
		missions[5][1].set_complete(true);
		current_mission = &missions[5][2];
		confirm_land_conflict();
		main_menu();
	}
}
void mission6_3() {//歡迎來到忍者村
	enter_mission(5, 2);
	missions[5][2].set_start(true);
	cin.ignore();
	my_cout("[呱頭蛙]：gualgual");
	my_cout("[你]：呱頭蛙，怎麼了？");
	my_cout("[呱頭蛙對著身後的樹使出泡沫]");
	my_cout("[熟悉男聲]：呱頭蛙，你進步了呢！");
	my_cout("[你]：三平！甲賀忍蛙！");
	my_cout("[三平]：好久不見" + player.get_name() + "！");
	my_cout("[你]：是呀！對了三平，這是現在跟我一起旅行的夥伴，希特隆和柚麗嘉！");
	my_cout("[希特隆]：你好！");
	my_cout("[柚麗嘉]：你好！");
	my_cout("[三平]：你們好！我是三平。");
	my_cout("[你]：三平，你在這裡做什麼呢？");
	my_cout("[三平]：我們村里要舉行慶典，我正在往回趕的路上。算算時間，明天就要舉行慶典了呢！");
	my_cout("[你]：咦？也就是說，這裡離忍者村不遠了嗎？");
	my_cout("[三平]：沒錯！你們有空的話，要不要也來參加呢？很熱鬧喔！");
	my_cout("[你]：好啊！");
	my_cout("\n[忍者村]");
	my_cout("[三平]：被巨石包圍，形成天然的壁壘。我們在裡頭自給自足，並延續忍術及忍者傳統");
	my_cout("[你]：那要怎麼進去呢？");
	my_cout("[三平]：從這兒");
	my_cout("[三平領著眾人走進一個沒有出口的洞穴]");
	my_cout("[你]：這兒是死路阿");
	my_cout("[三平]：等等");
	my_cout("[三平敲了敲石壁]");
	my_cout("[陌生男聲]：山");
	my_cout("[三平]：河");
	my_cout("[石壁打開了]");
	my_cout("[忍者村村民]：是三平回來啦！一平、二平，三平回來了！");
	my_cout("[一平]：三平，你回來了！這是你的朋友嗎？");
	my_cout("[三平]：是的！" + player.get_name() + "，這是我哥哥，一平還有二平");
	my_cout("[你]：你們好，我是" + player.get_name() + "！");
	my_cout("[希特隆]：我是希特隆");
	my_cout("[柚麗嘉]：我是柚麗嘉");
	my_cout("[二平]：你們好！歡迎來到忍者村！");
	my_cout("[半藏]：呦！這不是三平嗎？");
	my_cout("[三平]：頭領！");
	my_cout("[半藏]：回來了，先帶你的朋友回房間休息一下吧！晚點再跟村民們敘敘舊");
	my_cout("[三平]：是！");
	my_cout("\n[三平房間]");
	my_cout("[你]：明天的慶典感覺會很熱鬧很盛大呢！");
	my_cout("[三平]：是呀！因為這次慶典過後，半藏閣下就要從首領之位退位了！");
	my_cout("[希特隆]：咦？");
	my_cout("[三平]：接任的是我大哥，一平。他是目前忍者村內最強的忍者。我這次回來主要就是要幫幫我大哥");
	my_cout("[你]：幫忙？");
	my_cout("[三平]：嗯！往後就會以我們三兄弟為中心，守護忍者村");
	my_cout("[你]：加油囉，三普！");
	my_cout("[三平]：謝謝你！");
	my_cout("[外頭突然傳來一陣騷動]");
	my_cout("[你]：發生什麼事了？");
	my_cout("[三平]：是入侵警報！");
	my_cout("[二平]：三平！");
	my_cout("[三平]：二平哥");
	my_cout("[二平]：你先把" + player.get_name() + "他們帶去半藏閣下那兒，我出去找大哥");
	my_cout("[三平]：好！" + player.get_name() + "，你們跟我走！");
	my_cout("\n[頭領房間]");
	my_cout("[半藏]：三平，你來了！" + player.get_name() + "，你們也來了！");
	my_cout("[三平]：頭領，我先把他們放在你這兒，我出去找一平哥二平哥");
	my_cout("[半藏]：嗯！好孩子，你去...");
	my_cout("[頭領房門口突然湧入一群人與寶可夢]");
	my_cout("[三平]：你們是誰？");
	my_cout("[蒙面人]：忍者村的頭領半藏，跟我們走吧！");
	my_cout("[一隻阿利多斯使出之蜘蛛絲，倏忽間就將半藏帶走了！]");
	my_cout("[你]：你們...你們別跑！");
	my_cout("[三平]：我們追過去吧！");
	my_cout("[你]：好！");
	my_cout("[希特隆]：柚麗嘉，我們去跟一平二平說明情況！");
	my_cout("[柚麗嘉]：好！");
	my_cout("\n[三平]：從這兒！");
	my_cout("[突然有一個蒙面人現身]");
	my_cout("[蒙面人]：你們別想走！劈斬司令！");
	my_cout("[你]：出來吧，呱頭蛙！");
	my_cout("\n     [battle v.s. 蒙面人]");
	pokemon* assign[1] = { &Heidayu_Bisharp };
	choose_one_pokemon = &Frogadier;
	win_or_lose = whole_battle(1, 1, &Heidayu, assign);
	my_cout("[你]：呱頭蛙！還可以嗎？");
	my_cout("[蒙面人]：劈斬司令，暗影爪！");
	my_cout("[劈斬司令使出暗影爪]");
	my_cout("[一隻龜足巨鎧擋住了攻擊]");
	my_cout("[三平]：齋藏閣下！");
	my_cout("[齋藏]：我來遲了。龜足巨鎧，貝殼刃");
	my_cout("[龜足巨鎧使出貝殼刃]");
	my_cout("[劈斬司令失去戰鬥能力]");
	my_cout("[蒙面人]：劈斬司令！先回來吧。時間也拖夠了，忍術，葉遁");
	my_cout("[你]：三平，我們追");
	my_cout("[齋藏]：不要貿然追過去，我們先回村裡制定作戰計畫");
	my_cout(".\n.\n.\nTo be continued...");
	my_cout("\n[主線6-3 歡迎來到忍者村 completed]");
	my_cout("[獲得獎勵：銀莓果*5，好傷藥*10]");
	player.get_consumable(2)->add_num(5); player.get_consumable(8)->add_num(10);
	my_cout("[寶可夢經驗值上升]");
	minus_health();
	missions[5][2].set_complete(true);
	current_mission = &missions[5][3];
	confirm_land_conflict();
	main_menu();
}
void mission6_4() {//最終對決 你的甲賀忍蛙
	cout << "建議先將寶可夢的HP補滿！";
	enter_mission(5, 3);
	missions[5][3].set_start(true);
	cin.ignore();
	my_cout("[齋藏]：襲擊村莊的人是影伴");
	my_cout("[三平]：影伴大人？");
	my_cout("[齋藏]：嗯。影伴原本是忍者村的人，甚至幾乎被訂為半藏閣下的下一任頭領");
	my_cout("[你]：他這麼強啊...");
	my_cout("[齋藏]：但是，他的野心過於強大。忍者應該要將力量貢獻給世界，但他總想著要用忍者的力量奪取世界。");
	my_cout("[齋藏]：於是他就帶著他的同伴平田優離開了村子，並招募了一些弟子，組成忍者軍團");
	my_cout("[你]：那他們為什麼要襲擊忍者村呢？");
	my_cout("[齋藏]：因為他們要奪取忍者村的頭領之位。我發現這件事後，立刻趕回村子，卻還是來不及先告知頭領");
	my_cout("[三平]：那現在頭領到底在那兒？");
	my_cout("[一平]：別急，已經派村民分頭去找了");
	my_cout("[村民]：一平大人！");
	my_cout("[一平]：說人人到。找到頭領了嗎？");
	my_cout("[村民]：是，他們在鳳凰山山頂附近！");
	my_cout("[一平]：我們走吧");
	my_cout("\n[鳳凰山]");
	my_cout("[村民]：就在那上面了");
	my_cout("[熟悉男聲]：別想走！");
	my_cout("[你]：又是你。你就是平田優吧");
	my_cout("[平田優帶著一眾寶可夢擋在你們面前]");
	my_cout("[平田優]：沒錯！又見面了！");
	my_cout("[平田優]：進攻吧。");
	my_cout("[忍者軍團的寶可夢開始進攻]");
	my_cout("[三平]：一平哥，齋藏閣下，你們先走，這兒交給我們");
	my_cout("[一平]：好！三平，你們小心！");
	my_cout("[平田優]：劈斬司令，暗影爪。");
	my_cout("[劈斬司令使出暗影爪]");
	my_cout("[你]：呱頭蛙，我們迎戰吧");
	Heidayu_Bisharp.set_new_value(50, 25, 13);
	Heidayu.set_name("平田優");
	my_cout("\n     [battle v.s. 平田優]");
	pokemon* assign[1] = { &Heidayu_Bisharp };
	choose_one_pokemon = &Frogadier;
	win_or_lose = whole_battle(1, 1, &Heidayu, assign);
	my_cout("[你]：剛剛...剛剛那是什麼？");
	my_cout("[三平]：" + player.get_name() + "，快來，一平哥跟齋藏閣下他們還在上面");
	my_cout("[你]：好！");
	my_cout("\n[鳳凰山山頂]");
	my_cout("[影伴]：瑪狃拉，暗襲要害");
	my_cout("[瑪狃拉使出暗襲要害]");
	my_cout("[一平]：甲賀忍蛙，影分身");
	my_cout("[甲賀忍蛙使出影分身]");
	my_cout("[影伴]：瑪狃拉，躲開");
	my_cout("[瑪狃拉一一躲開分身]");
	my_cout("[一平]：還沒完呢");
	my_cout("[影伴]：在地下！");
	my_cout("[甲賀忍蛙擊中閃避不及的瑪狃拉]");
	my_cout("[一平]：甲賀忍蛙，最後一擊，水手裡劍！");
	my_cout("[甲賀忍蛙使出水手裡劍]");
	my_cout("[瑪狃拉失去戰鬥能力]");
	my_cout("[影伴]：瑪狃拉，快起來戰鬥！");
	my_cout("[影伴]：...我...已經輸了嗎...");
	my_cout("[半藏]：影伴，你知道你比一平更缺少什麼嗎？");
	my_cout("[影伴]：什麼？");
	my_cout("[半藏]：那就是獻身。他會為了忍者村的夢想、忍者村裡所有人以及所有寶可夢的未來戰鬥");
	my_cout("[半藏]：為了世界、為了人類、為了寶可夢。那才是忍者，也是你們的勝敗關鍵");
	my_cout("[半藏]：他相信自己、相信甲賀忍蛙，戰鬥到了最後");
	my_cout("[一平]：您的瑪狃拉戰鬥得很出色，請好好表揚他吧");
	my_cout("[影伴]：一平...");
	my_cout("[影伴]：瑪狃拉，辛苦了，你做得很好");
	my_cout("[一平]：您是一名好忍者，希望您能將您的力量貢獻給世界");
	my_cout("[半藏]：我們回村子吧");
	my_cout("\n[忍者村]");
	my_cout("[希特隆]：恭喜你呀，甲賀忍蛙、" + player.get_name());
	my_cout("[三平]：恭喜你！這樣現場就有三隻甲賀忍蛙了呢！");
	my_cout("[你]：謝謝你們！");
	my_cout("[三平]：辛苦了！今晚好好休息吧！明天要好好體驗我們忍者村的慶典喔！");
	my_cout("[你]：好！");
	my_cout("\n[隔天，忍者村外]");
	my_cout("[你]：慶典真的很有趣呢！謝謝你們的招待");
	my_cout("[三平]：不客氣！我們也很高興你們能來參加");
	my_cout("[你]：我們要繼續我們的旅程了！希望下次再見時，我們都能變得更強！");
	my_cout("[三平]：一定的！我們也會為了忍者村的未來而努力！希特隆、柚麗嘉、" + player.get_name() + "再見啦！");
	my_cout("[經歷了混亂的一天，你帶著更多與夥伴們的羈絆微笑離去，而你們的旅程還將繼續]");
	my_cout(".\n.\n.\nTo be continued...");
	my_cout("\n[主線6-4 最終對決 你的甲賀忍蛙 completed]");
	my_cout("[獲得獎勵：銀莓果*5，三明治*5]");
	player.get_consumable(2)->add_num(5); player.get_consumable(5)->add_num(5);
	my_cout("[寶可夢經驗值上升]");
	minus_health();
	missions[5][3].set_complete(true);
	current_mission = &missions[6][0];
	confirm_land_conflict();
	main_menu();
}

void mission7_1() {//相同的呼吸 翔太的蜥蜴王
	enter_mission(6, 0);
	missions[6][0].set_start(true);
	cin.ignore();
	my_cout("\n~~~~~主線第七章 開始~~~~~");
	my_cout("[你]：天氣變得越來越冷了");
	my_cout("[皮卡丘]：皮卡皮卡");
	my_cout("[希特隆]：是呀！過了這座森林，就進入映雪市囉");
	my_cout("[柚麗嘉]：哥哥，我們可以先在這兒休息一下嗎？");
	my_cout("[希特隆]：柚麗嘉累了啊..." + player.get_name() + "我們能在這兒停一下嗎？");
	my_cout("[你]：好啊！我們在這兒休息一下吧！");
	my_cout("[熟悉男聲]：咦？" + player.get_name() + "！是" + player.get_name() + "嗎？");
	my_cout("[你]：咦？翔太！");
	my_cout("[翔太]：好久不見！你們怎麼在這兒？是要去挑戰映雪道館嗎？");
	my_cout("[你]：是呀！你也是嗎？");
	my_cout("[翔太]：不...聽說映雪道館很難對付，我的寶可夢又屬性不利");
	my_cout("[你]：這樣啊...");
	my_cout("[翔太]：不過，" + player.get_name() + "，我可以跟你來場對戰嗎？我想知道自己這段時間究竟成長了多少。");
	my_cout("[你]：好啊！我們來場3對3吧！");
	my_cout("[希特隆]：" + player.get_name());
	my_cout("[你]：怎麼了，希特隆？");
	my_cout("[希特隆]：你找個機會用一下甲賀忍蛙，關於忍者村那場對戰的狀態，我認為有必要研究一下");
	my_cout("\n     [battle v.s. 翔太]");
	pokemon* assign[3] = { &Shelgon,&Honedge,&Sceptile };
	win_or_lose = whole_battle(3, 3, &Sawyer, assign);
	my_cout("[希特隆]：蜥蜴王失去戰鬥能力，所以是" + player.get_name() + "獲勝");
	my_cout("[戰鬥結束，你與甲賀忍蛙同時跪坐在地]");
	my_cout("[你]：翔太，我贏囉！");
	my_cout("[翔太]：還是贏不了你呀！但是我獲得了很好的經驗。對了，剛剛那是什麼啊？要怎麼做才能達到剛剛那種狀態？請告訴我");
	my_cout("[你]：這...這我也不清楚啊...");
	my_cout("[皮卡丘]：皮卡皮卡");
	my_cout("[希特隆]：至今為止也只有幾次而已...");
	my_cout("[你]：我也不知道該怎麼說...就好像忍蛙所看到的、所做的事，我也在做、在看一樣");
	my_cout("[翔太]：這是...合體了嗎？");
	my_cout("[你]：我也不知道...然後全身就會變得很熱血，但戰鬥完會覺得特別累");
	my_cout("[翔太]：也就是說你變成忍者蛙了");
	my_cout("[眾人]：欸？");
	my_cout("[翔太]：我得走了，" + player.get_name() + "、希特隆、柚麗嘉，還得趕路呢！");
	my_cout("[你]：下次再對戰吧！");
	my_cout("[翔太]：我下次會追上你的！掰掰啦！");
	my_cout("[你]：我們也走吧！");
	my_cout("[陌生男聲]：不好意思，等一下！");
	my_cout("[你]：咦？");
	my_cout(".\n.\n.\nTo be continued...");
	my_cout("\n[主線7-1 相同的呼吸 翔太的蜥蜴王 completed]");
	my_cout("[獲得獎勵：銀莓果*5，好傷藥*10]");
	player.get_consumable(2)->add_num(5); player.get_consumable(8)->add_num(10);
	my_cout("[寶可夢經驗值上升]");
	minus_health();
	missions[6][0].set_complete(true);
	current_mission = &missions[6][1];
	confirm_land_conflict();
	main_menu();
}
void mission7_2() {//mega對決 超級噴火龍
	//cout << "建議先將寶可夢的HP補滿！";
	enter_mission(6, 1);
	missions[6][1].set_start(true);
	cin.ignore();
	my_cout("[陌生男聲]：我叫艾嵐，這是我的夥伴，噴火龍");
	my_cout("[你]：噴火龍，你好啊！等等，他脖子上的那個難不成是...mega進化石？");
	my_cout("[艾嵐]：沒錯！要看看嗎？讓我的噴火龍跟你的甲賀忍蛙對戰");
	my_cout("[你]：欸？忍蛙嗎？");
	my_cout("[艾嵐]：我看了你剛剛那場對戰，再讓我見識一次吧！");
	my_cout("[你]：好啊！甲賀忍蛙，出來吧！");
	my_cout("\n     [battle v.s. 艾嵐]");
	pokemon* assign[1] = { &Charizard };
	choose_one_pokemon = &Greninja;
	win_or_lose = whole_battle(1, 1, &Alain, assign);
	if (win_or_lose == false) {
		my_cout("[希特隆]：甲賀忍蛙失去戰鬥能力，所以是艾嵐獲勝");
		my_cout("[你與甲賀忍蛙應聲倒地]");
		my_cout("[柚麗嘉]：" + player.get_name() + "！");
		my_cout("[你]：我沒事！甲賀忍蛙，你還好嗎？");
		my_cout("[甲賀忍蛙]：geko");
		my_cout("[你]：這樣啊！我也是呢");
		my_cout("[你]：艾嵐，下次相見請再和我們戰鬥吧！");
		my_cout("[艾嵐]：嗯！對了，你還沒有自我介紹呢");
		my_cout("[你]：啊，抱歉！我叫" + player.get_name());
		my_cout("[艾嵐]：嗯，" + player.get_name() + "下次見面我們再來對戰吧！我先離開囉！");
		my_cout("[你]：掰掰！");
		my_cout("[你]：到底為什麼會有剛剛那種狀態呢...");
		my_cout("[甲賀忍蛙]：geko");
		my_cout("[希特隆]：試著分析看看吧，用科學總能明白些什麼的");
		my_cout("[你]：嗯！那就拜託你了，希特隆！");
		my_cout("[希特隆]：但首先，我們得先繼續前往映雪市啦！你得拿到第八枚徽章才行呢！");
		my_cout("[你]：對喔！我們繼續前進吧！");
		my_cout(".\n.\n.\nTo be continued...");
		my_cout("\n[主線7-2 mega對決 超級噴火龍 completed]");
		my_cout("[獲得獎勵：銀莓果*5，好傷藥*10]");
		player.get_consumable(2)->add_num(5); player.get_consumable(8)->add_num(10);
		my_cout("[寶可夢經驗值上升]");
		minus_health();
		missions[6][1].set_complete(true);
		current_mission = &missions[6][2];
		confirm_land_conflict();
		main_menu();
	}
}
void mission7_3() {//憤怒的雷擊 閃電鳥與嗡蝠
	enter_mission(6, 2);
	missions[6][2].set_start(true);
	cin.ignore();
	my_cout("[柚麗嘉]：哥哥你走慢點！");
	my_cout("[你]：希特隆真的很興奮呢");
	my_cout("[希特隆]：當然！前面那個村落即將舉行閃電鳥祭，作為電系道館館主，我一定要目睹閃電鳥的風采呀！");
	my_cout("[柚麗嘉]：可以看到閃電鳥？");
	my_cout("[希特隆]：是阿！");
	my_cout("[你]：欸...希特隆...閃電鳥是...那個嗎？");
	my_cout("[希特隆]：閃電鳥已經到了？那我們得加快腳步才...");
	my_cout("[柚麗嘉]：哥哥小心！");
	my_cout("[閃電鳥使出雷擊，希特隆身後的樹木應聲倒地]");
	my_cout("[你]：希特隆！");
	my_cout("[希特隆]：我沒事！");
	my_cout("[你]：不行，這樣太危險了，剛剛走來的路上我有看到一個洞穴，我們先去暫避一下吧");
	my_cout("[柚麗嘉]：好！");
	my_cout("\n[洞穴內]");
	my_cout("[你]：這裡應該安全了");
	my_cout("[陌生男聲]：你們...");
	my_cout("[你]：是誰在那？");
	my_cout("[陌生男聲]：抱歉，我是救護隊的，我叫雷克斯");
	my_cout("[你]：欸，你的腿怎麼了？");
	my_cout("[雷克斯]：我剛剛開著救援車要回鎮上，但被閃電鳥的雷擊擊中，因此出了車禍");
	my_cout("[你]：不行...你這傷，得趕快救治");
	my_cout("[突然又一陣轟隆作響]");
	my_cout("[希特隆]：入口...入口被掉落的岩石堵住了...");
	my_cout("[你]：這樣不行，我們得想辦法出去。嗡蝠，出來吧！");
	my_cout("[嗡蝠]：gugu");
	my_cout("[你]：我們繼續往內走。嗡蝠，你能幫我們找到出口嗎？");
	my_cout("[嗡蝠]：gugu");
	my_cout("[你]：我們走吧！");
	my_cout("[希特隆]：克雷斯先生，扶著我吧");
	my_cout("[雷克斯]：謝謝！");
	my_cout("\n[洞穴出口]");
	my_cout("[你]：謝謝你，嗡蝠！我們快出去吧！");
	my_cout("[又一次轟隆作響]");
	my_cout("[希特隆]：閃電鳥？他怎麼在這裡？");
	my_cout("[嗡蝠]：gugu");
	my_cout("[武藏]：既然你...誠心誠意地說了「gugu」");
	my_cout("[小次郎]：我們就大發慈悲的...回答你");
	my_cout("[武藏]：為了...防止世界被破壞");
	my_cout("[小次郎]：為了守護世界的...和平");
	my_cout("[武藏]：貫徹愛與真實的...邪惡");
	my_cout("[小次郎]：可愛...又迷人的反派角色");
	my_cout("[武藏]：武藏...");
	my_cout("[小次郎]：小次郎...");
	my_cout("[武藏]：我們是...穿梭在宇宙間的...火箭隊二人組");
	my_cout("[小次郎]：白洞...白色的明天正等著...我們");
	my_cout("[喵喵]：就是這樣...喵~");
	my_cout("[你]：火箭隊？你們怎麼成了這副髒兮兮的樣子？");
	my_cout("[喵喵]：不說了...我們先走了");
	my_cout("[你]：站住！這是你們做得好事吧？");
	my_cout("[武藏]：我們只是像平常一樣想抓隻寶可夢立功...結果...");
	my_cout("[希特隆]：唉...");
	my_cout("[你]：我出去跟閃電鳥說清楚吧，希特隆，柚麗嘉，你們在這裡照顧克雷斯先生，拜託了");
	my_cout("[希特隆]：好，你小心點");
	my_cout("[你]：閃電鳥！我們不是敵...");
	my_cout("[閃電鳥使出充電光束]");
	my_cout("[你]：閃電鳥，冷靜一點。我們一起去參加閃電鳥祭，好ㄇ...");
	my_cout("[閃電鳥使出充電光束]");
	my_cout("[你]：不行，這樣不行！我們只能戰鬥了！出來吧，摔跤鷹人");
	my_cout("[摔跤鷹人]：cholu");
	my_cout("[你]：摔跤鷹人，飛膝踢");
	my_cout("[摔跤鷹人使出飛膝踢，正中閃電鳥]");
	my_cout("[你]：太好了！摔跤鷹人！再一次，飛膝踢");
	my_cout("[摔跤鷹人使出飛膝踢]");
	my_cout("[摔跤鷹人]：cholu！");
	my_cout("[閃電鳥使出充電光束]");
	my_cout("[你]：小心！摔跤鷹人");
	my_cout("[摔跤鷹人被閃電鳥擊中，墜落山谷");
	my_cout("[你]：摔跤鷹人！");
	my_cout("[嗡蝠]：gu gugugugugu");
	my_cout("[嗡蝠飛衝出去試圖接住摔跤鷹人。此時，嗡蝠周遭圍繞著白色的光");
	player.evolution(&Noibat);
	my_cout("[你]：這是...");
	my_cout("[嗡蝠進化成音波龍]");
	my_cout("[音波龍]：bua");
	my_cout("[你]：進化了...");
	my_cout("[你]：摔跤鷹，辛苦了。音波龍，謝謝你！");
	my_cout("[音波龍]：bua buabua");
	my_cout("[你]：音波龍，你想戰鬥嗎？");
	my_cout("[音波龍]：bua");
	my_cout("[音波龍使出爆音波]");
	my_cout("[你]：閃電鳥！我們真的不是敵人，現在這裡有一名傷患，你可以讓我們出去嗎？");
	my_cout("[閃電鳥停止攻擊，並飛到洞口前，示意你們出去]");
	my_cout("[你]：謝謝你，閃電鳥！");
	my_cout("[你]：希特隆，柚麗嘉，我們快走吧！");
	my_cout("[希特隆]：好！");
	my_cout("\n[小鎮內]");
	my_cout("[雷克斯]：謝謝你們把我送回來！");
	my_cout("[你]：不客氣！");
	my_cout("[雷克斯]：閃電鳥祭快要開始，你們不是想看嗎？");
	my_cout("[你]：是！希特隆，柚麗嘉，我們快去吧！");
	my_cout("[村民]：開始放煙火囉！");
	my_cout("[你]：好美啊！");
	my_cout("[希特隆]：那是...閃電鳥！");
	my_cout("[音波龍]：bua");
	my_cout("[你]：音波龍，今天真的謝謝你！");
	my_cout("[音波龍]：bua");
	my_cout(".\n.\n.\nTo be continued...");
	my_cout("\n[主線7-3 憤怒的雷擊 閃電鳥與嗡蝠 completed]");
	my_cout("[獲得獎勵：銀莓果*5，好傷藥*10]");
	player.get_consumable(2)->add_num(5); player.get_consumable(8)->add_num(10);
	my_cout("[寶可夢經驗值上升]");
	minus_health();
	missions[6][2].set_complete(true);
	current_mission = &missions[6][3];
	confirm_land_conflict();
	main_menu();
}
void mission7_4() {//再遇艾嵐
	enter_mission(6, 3);
	missions[6][3].set_start(true);
	cin.ignore();
	my_cout("[希特隆]：" + player.get_name() + "，我從你之前的對戰發現的一些事情");
	my_cout("[你]：是什麼？");
	my_cout("[希特隆]：甲賀忍蛙狀態變化時，你們的動作會變得同步。我猜，這種變化的成因可能跟你們的情緒變化有關係");
	my_cout("[你]：情緒變化？");
	my_cout("[希特隆]：對！所以...這是我的新發明！脈動偵測器與迷你史特洛伊德！你們在戰鬥中戴上這個脈動偵測器，迷你史特洛伊德就會幫忙分析、即時顯現你們的情緒變化");
	my_cout("[你]：哇！真是太厲害了！謝謝你，希特隆！");
	my_cout("[你]：不如我們現在就來場對...");
	my_cout("[熟悉男聲]：這不是" + player.get_name() + "嗎？");
	my_cout("[你]：艾嵐！");
	my_cout("[艾嵐]：又見面了！咦，這是什麼？");
	my_cout("[希特隆]：這是我的新發明！脈動偵測器與迷你史特洛伊德！研究甲賀忍蛙的特殊狀態用的");
	my_cout("[艾嵐]：哦！不如我們來場對戰吧！我的噴火龍對上你的甲賀忍蛙");
	my_cout("[你]：嗯...艾嵐，你還有其他寶可夢嗎？機會難得，我們讓其他寶可夢也戰鬥看看吧！");
	my_cout("[艾嵐]：好！就是你了，金屬怪！");
	my_cout("\n     [battle v.s. 艾嵐]");
	pokemon* assign[1] = { &Metagross };
	win_or_lose = whole_battle(1, 1, &Alain, assign);
	if (win_or_lose == false) {
		my_cout("[希特隆]：這場對戰由艾嵐獲勝");
		my_cout("[你]：艾嵐真是無懈可擊呢！");
		my_cout("[艾嵐]：謝謝你！這次的對戰真是太有趣了！接著就是他們了吧");
		my_cout("[你]：嗯！當然！甲賀忍蛙，出來吧");
	}
	else {
		my_cout("[希特隆]：這場對戰由" + player.get_name() + "獲勝");
		my_cout("[你]：終於報上次的一箭之仇了");
		my_cout("[艾嵐]：真要報一箭之仇還是得讓本人來吧？");
		my_cout("[你]：嗯！當然！甲賀忍蛙，出來吧");
	}
	my_cout(".\n.\n.\nTo be continued...");
	my_cout("\n[主線7-4 再遇艾嵐 completed]");
	my_cout("[獲得獎勵：銀莓果*5，好傷藥*10]");
	player.get_consumable(2)->add_num(5); player.get_consumable(8)->add_num(10);
	my_cout("[寶可夢經驗值上升]");
	minus_health();
	missions[6][3].set_complete(true);
	current_mission = &missions[6][4];
	confirm_land_conflict();
	main_menu();
}
void mission7_5() {//二次對決 甲賀忍蛙與mega噴火龍
	//cout << "建議先將寶可夢的HP補滿！\n";
	enter_mission(6, 4);
	missions[6][4].set_start(true);
	cin.ignore();
	my_cout("[艾嵐]：噴火龍，上囉");
	my_cout("\n     [battle v.s. 艾嵐]");
	pokemon* assign[1] = { &Charizard };
	choose_one_pokemon = &Greninja;
	win_or_lose = whole_battle(1, 1, &Alain, assign);
	if (win_or_lose == false) {
		my_cout("[你]：我的身體怎麼突然動不了？");
		my_cout("[希特隆]：這是...這是...脈衝到剛剛都是重合的，怎麼突然分開了？");
		my_cout("[你]：甲賀忍蛙...我...");
		my_cout("[你與甲賀忍蛙同時昏倒在地]");
		my_cout("[柚麗嘉]：" + player.get_name() + "！");
		my_cout("[艾嵐]：" + player.get_name() + "、甲賀忍蛙！");
		cout << "請原地休息5秒\n";
		this_thread::sleep_for(chrono::seconds(5));
		my_cout("[皮卡丘]：皮卡皮卡");
		my_cout("[你]：皮卡丘，大家都在啊");
		my_cout("[希特隆]：你醒了！沒事吧？");
		my_cout("[你]：我...我沒事！甲賀忍蛙呢？");
		my_cout("[希特隆]：他也沒事！");
		my_cout("[甲賀忍蛙]：geko");
		my_cout("[你]：抱歉阿艾嵐，就這樣中斷比賽了");
		my_cout("[艾嵐]：沒事！你先休息吧！今天這樣是平手，下次要分出勝負才行呢！");
		my_cout("[你]：嗯！艾嵐你會參加聯盟戰吧！");
		my_cout("[艾嵐]：聯盟戰？沒有欸");
		my_cout("[柚麗嘉]：欸？沒有嗎？我以為你肯定會參加的");
		my_cout("[你]：聯盟戰會有很多厲害的訓練家，好期待呀！");
		my_cout("[艾嵐]：聽起來很有趣呢");
		my_cout("[你]：不如，我們就約在那，下次對戰的地方！");
		my_cout("[艾嵐]：道館戰...嗎？聽起來很不錯");
		my_cout("[你]：下次見面之前，我們兩個會掌握好力量的，就在那個殿堂決戰吧！");
		my_cout("[艾嵐]：好！我會等你的！");
		my_cout("[你與勁敵立下了約定，誓言在最高的殿堂相見。雖然你與甲賀忍蛙身上還有許多未知的謎團，但你一定會找出答案，因為，你們的旅程還將繼續]");
		my_cout(".\n.\n.\nTo be continued...");
		my_cout("\n[主線7-5 二次對決 甲賀忍蛙與mega噴火龍 completed]");
		my_cout("[獲得獎勵：銀莓果*5，好傷藥*10]");
		player.get_consumable(2)->add_num(5); player.get_consumable(8)->add_num(10);
		my_cout("[寶可夢經驗值上升]");
		minus_health();
		missions[6][4].set_complete(true);
		current_mission = &missions[7][0];
	}
}

void mission8_1() {//宿敵的對決3
	enter_mission(7, 0);
	missions[7][0].set_start(true);
	cin.ignore();
	my_cout("\n~~~~~主線第八章 開始~~~~~");
	my_cout("[你]：終於來到映雪道館了！這次也要一舉拿下徽章...");
	my_cout("[希特隆]：等一下" + player.get_name() + "現在都已經傍晚了，人家道館已經關了啦！明天再來吧");
	my_cout("[你]：啊...好吧...那我們就在這裡休息一晚吧");
	my_cout("[熟悉男聲]：" + player.get_name() + "！");
	my_cout("[你]：咦？翔太！你怎麼在這？");
	my_cout("[翔太]：我集齊八枚徽章，可以挑戰聯盟了！我記得你上次說要來挑戰映雪道館，沒想到真的能遇到！怎麼樣？拿到徽章了嗎？");
	my_cout("[你]：還沒呢！今天到館已經關了，只能明天再來了");
	my_cout("[翔太]：這樣啊...還是你要先與我對戰一場，熱身一下？");
	my_cout("[你]：好啊！一樣來場3對3吧！最後一隻讓我看看你的蜥蜴王吧，我也會讓甲賀忍蛙上來一戰的");
	my_cout("[希特隆]：" + player.get_name() + "，一樣戴上脈衝偵測器吧");
	my_cout("[你]：好。翔太，來吧！");
	my_cout("\n     [battle v.s. 翔太]");
	Sceptile.set_new_value(100, 27, 65);
	Greninja.set_mega_ability(false);
	pokemon* assign[3] = { &Doublade,&Clawitzer,&Sceptile };
	win_or_lose = whole_battle(3, 3, &Sawyer, assign);
	if (win_or_lose == false) {
		my_cout("[希特隆]：這場對戰由翔太獲勝！");
		my_cout("[翔太]：我...我贏了...我贏過" + player.get_name() + "了");
		my_cout("[你]：甲賀忍蛙...你還好嗎？");
		my_cout("[甲賀忍蛙]：geko");
		my_cout("[你]：我們輸了呢！");
		my_cout("[皮卡丘]：皮卡皮卡");
		my_cout("[甲賀忍蛙]：geko");
		my_cout("[你]：翔太，恭喜你呀！你真的進步很多");
		my_cout("[翔太]：謝謝！");
		my_cout("[翔太]：" + player.get_name() + "，明天的道館戰，我會去幫你加油的！");
		my_cout("[你]：謝謝你，翔太！");
		my_cout("[你]：希特隆，為什麼...今天甲賀忍蛙的狀態沒有改變呢？");
		my_cout("[希特隆]：我也不清楚，只是今天脈衝確實完全沒有重合");
		my_cout("[你]：這樣啊...");
		my_cout("[希特隆]：你也先別灰心，說不定明天到館戰時就會恢復了");
		my_cout("[你]：嗯！謝謝你，希特隆！");
		my_cout("[你]：但願如此吧...");
		my_cout(".\n.\n.\nTo be continued...");
		my_cout("\n[主線8-1 宿敵的對決3 completed]");
		my_cout("[獲得獎勵：銀莓果*5，三明治*5]");
		player.get_consumable(2)->add_num(5); player.get_consumable(5)->add_num(5);
		my_cout("[寶可夢經驗值上升]");
		minus_health();
		missions[7][0].set_complete(true);
		current_mission = &missions[7][1];
		confirm_land_conflict();
		main_menu();
	}
}
void mission8_2() {//一場不尋常的對戰
	enter_mission(7, 1);
	missions[7][1].set_start(true);
	cin.ignore();
	my_cout("[你]：今天就是映雪道館的道館戰了！");
	my_cout("[希特隆]：" + player.get_name() + "，你準備好了嗎？");
	my_cout("[你]：嗯！我一定要拿下這枚徽章！走吧");
	my_cout("[你]：我要挑戰道館戰，麻煩了！");
	my_cout("[對戰裁判員]：裡面...道館裡面很冷...麻煩挑戰者...做好禦寒準備再進來...阿嚔");
	my_cout("[你]：您沒事吧？");
	my_cout("[對戰裁判員]：我...我沒事...準備好了就...請進吧...阿嚔");
	my_cout("[你]：謝謝您！我準備好了");
	my_cout("[館主]：那什麼...你們幾個，來的正好啊");
	my_cout("[你]：是！道館戰就拜託了！");
	my_cout("[館主]：嗯，我叫德撫，就是那啥...映雪道館的館主");
	my_cout("[你]：我是來自" + player.get_loc() + "的" + player.get_name());
	my_cout("[德撫]：有幾個徽章了？");
	my_cout("[你]：我有七枚徽章了！");
	my_cout("[德撫]：那麼這就是關係到最後一枚徽章的道館戰了。我很期待喔！");
	my_cout("[你]：是！");
	my_cout("[德撫]：那麼那什麼...我們就開始吧！");
	my_cout("\n     [battle v.s. 德撫]");
	pokemon* assign[3] = { &Abomasnow,&Avalugg,&Bergmite };
	my_cout("\n[對戰裁判員]：現在開始挑戰者" + player.get_name() + "與館主德撫的對戰...阿嚔");
	my_cout("[對戰裁判員]：使用的寶可夢為三隻，若有一方的寶可夢全數失去戰鬥能力則對戰結束。只有挑戰者可以進行寶可夢的替換...阿嚔");
	my_cout("[德撫]：首先是你！暴雪王，出來吧！");
	win_or_lose = whole_battle(3, 3, &Wulfric, assign);
	if (win_or_lose == false) {
		my_cout("[對戰裁判員]：這場對戰由館主德撫獲勝！");
		my_cout("[你]：我輸了嗎？");
		my_cout("[皮卡丘]：皮卡皮卡");
		my_cout("[德撫]：像水那樣，能配合著容器改變自己的形狀，但本質卻不變");
		my_cout("[德撫]：我是因為辦不到那樣，才愛著冰系寶可夢的。你又如何呢？");
		my_cout("[你]：......");
		my_cout("[德撫]：能去到多遠取決於你有多信賴你的寶可夢");
		my_cout("[德撫]：抱歉，看來我還不能把徽章給你呢");
		my_cout("[你]：......");
		my_cout(".\n.\n.\nTo be continued...");
		my_cout("\n[主線8-2 一場不尋常的對戰 completed]");
		my_cout("[獲得獎勵：銀莓果*5，好傷藥*5]");
		player.get_consumable(2)->add_num(5); player.get_consumable(8)->add_num(5);
		my_cout("[寶可夢經驗值上升]");
		minus_health();
		missions[7][1].set_complete(true);
		current_mission = &missions[7][2];
		confirm_land_conflict();
		main_menu();
	}
}
void mission8_3() {//迷幻森林 進化的黎明
	enter_mission(7, 2);
	missions[7][2].set_start(true);
	cin.ignore();
	my_cout("[喬伊小姐]：他不管是身體還是精神上都受了極大損傷，需要多休息一下");
	my_cout("[你]：了解了，謝謝您，我去看看他");
	my_cout("[你]：甲賀忍蛙，抱歉阿...要是我能更振作點...要是我能更振作點的話...應該能引發出你的力量的");
	my_cout("[你]：你休息吧");
	my_cout("[希特隆]：怎麼樣？");
	my_cout("[你]：沒事，只是需要多休息。我想一個人待一下");
	my_cout("[皮卡丘]：皮卡皮卡");
	my_cout("[你]：抱歉，皮卡丘，你也別跟過來");
	my_cout("[皮卡丘]：皮卡");
	my_cout("\n[森林]");
	my_cout("[你]：我該更振作的...我該");
	my_cout("[你]：我該...怎麼做...");
	my_cout("[你就這樣在雪地上躺著想了一夜，你不知道的是，甲賀忍蛙也坐在森林裡某棵樹的樹枝上，想了一整夜...]");
	my_cout("\n[你]：啊啊啊啊啊啊........");
	my_cout("[你]：算了，不想了，不想了。這麼一個人靜靜地思考才不像我的風格。");
	my_cout("[你]：搞不懂的時候先行動就對了喔啊啊啊！！");
	my_cout("[你向後踩空，一路滾到了山坡下]");
	my_cout("[你]：哈哈！哈哈哈哈哈！居然跌下來了！");
	my_cout("[你]：咦，下雪了呢，得快點回去否則大家會擔心...");
	my_cout("[你]：不，這雪...似乎有點兒太大...我先在旁邊的洞穴躲躲吧");
	my_cout("[你走進洞穴裡，發現有許多野生寶可夢在看著你]");
	my_cout("[你]：各位，一起進來躲雪吧！");
	my_cout("[你]：下雪時果然還是要大家窩在一起才不冷呢！");
	my_cout("[突然間你聽到遠方傳來淒厲的叫聲]");
	my_cout("[你]：這是...？我去看看狀況，你們好好待在這兒喔！");
	my_cout("[你走出洞穴，發現一窩粉蝶蛹困在樹枝上，搖搖欲墜]");
	my_cout("[你]：別怕，我馬上就來救你們！");
	my_cout("[你爬上樹，把粉蝶蛹一一抱下來，放在地上]");
	my_cout("[你]：還差最後一隻！但你距離有點遠啊。來吧，抓住我！");
	my_cout("[你]：勇敢跳過來！");
	my_cout("[你]：很好！我馬上帶你下去！");
	my_cout("[就在此時，你們所在的樹枝斷裂了]");
	my_cout("[你]：啊啊啊啊啊啊！！！");
	my_cout("[掉落到一半，你忽然感覺到有個東西緊緊纏住你的腰，而你也停止下墜]");
	my_cout("[你]：甲賀忍蛙！");
	my_cout("[甲賀忍蛙]：geko");
	my_cout("[你]：謝謝你，甲賀忍蛙");
	my_cout("[你]：我們回去吧！");
	my_cout("[忽然一陣大風吹來，一隻粉蝶蛹被吹到懸崖外]");
	my_cout("[你]：粉蝶蛹！要救他！我們倆一起，能做到");
	my_cout("[甲賀忍蛙周遭圍繞著白色的光]");
	my_cout("[你]：甲賀忍蛙，去吧！閃過凸出來的樹枝！");
	my_cout("[甲賀忍蛙]：geko");
	my_cout("[你]：要減速囉！");
	my_cout("[甲賀忍蛙]：geko");
	my_cout("[你]：成功啦！");
	my_cout("[甲賀忍蛙]：geko");
	my_cout("\n[洞穴內]");
	my_cout("[你]：沒事囉，大家！");
	my_cout("[甲賀忍蛙變回一般型態]");
	my_cout("[你]：甲賀忍蛙，謝謝你！抱歉，讓你擔心了");
	my_cout("[甲賀忍蛙]：geko");
	my_cout("[你]：我小時候也發生過這種事呢！那時，我想見寶可夢，就一個人跑進了森林，結果迷了路。那時，也跟一群寶可夢們在樹洞下躲雨");
	my_cout("[你]：抱歉，忍者蛙。明明說好要一起變強的。");
	my_cout("[你]：剛剛在救粉蝶蛹時，我想通了。因為想要快點拿到徽章，我想我著急了");
	my_cout("[你]：想著身為訓練家的我，不再加把勁是不行的。但這樣，不是我們一起加油啊，我身邊明明還有你們呢！");
	my_cout("[你]：剛剛我想著要跟你一起救粉蝶蛹，正因為有你在，所以力量湧現出來了");
	my_cout("[你]：甲賀忍蛙，把你的力量借給我吧！我們再一次從頭開始");
	my_cout("[你]：然後...然後一起去我們約好的地方");
	my_cout("[甲賀忍蛙]：geko");
	my_cout("[你]：雪停了呢。大家，再見囉！粉蝶蛹，保重！");
	my_cout("[此時，六隻粉蝶蛹的周遭都圍繞著白色的光]");
	my_cout("[粉蝶蛹進化成彩粉蝶]");
	my_cout("[你]：哇！好漂亮！");
	my_cout("[彩粉蝶翩翩飛去，點亮了夜空]");
	my_cout("[你]：甲賀忍蛙，我們回去吧！");
	my_cout("[甲賀忍蛙]：geko");
	my_cout(".\n.\n.\nTo be continued...");
	my_cout("\n[主線8-3 迷幻森林 進化的黎明 completed]");
	my_cout("[獲得獎勵：銀莓果*5，好傷藥*5]");
	player.get_consumable(2)->add_num(5); player.get_consumable(8)->add_num(5);
	Greninja.set_mega_ability(true);
	my_cout("[寶可夢經驗值上升]");
	minus_health();
	missions[7][2].set_complete(true);
	current_mission = &missions[7][3];
	confirm_land_conflict();
	main_menu();
}
void mission8_4() {//發動巨型水手裡箭 對決超級暴雪王
	enter_mission(7, 3);
	if (missions[7][3].get_start() == false) {
		missions[7][3].set_start(true);
		cin.ignore();
		my_cout("[你]：再一次挑戰道館，我們走吧");
		my_cout("[希特隆]：" + player.get_name() + "，你還好嗎？");
		my_cout("[你]：嗯！不會再迷惘了，這次會好好注視前方的");
		my_cout("[希特隆]：加油！要拿到第八個徽章喔！");
		my_cout("[你]：嗯！我一定會的！");
		my_cout("[你]：我要挑戰道館戰，麻煩了！");
		my_cout("[德撫]：總算來了呢！是復仇戰嗎？");
		my_cout("[你]：是！我要拿下這枚徽章！");
		my_cout("[德撫]：那麼我們就趕緊開始吧！看你的眼神，這會是場精彩的對決呢！");
		my_cout("[德撫]：用你的熱情還融化我的堅冰吧，挑戰者！去吧，冰...");
		my_cout("[對戰裁判員]：等一下，還沒宣讀規則呢！");
		my_cout("[德撫]：規則？啊...那什麼，你快唸吧");
	}
	my_cout("\n     [battle v.s. 德撫]");
	my_cout("\n[對戰裁判員]：現在開始挑戰者" + player.get_name() + "與館主德撫的對戰");
	my_cout("[對戰裁判員]：使用的寶可夢為三隻，若有一方的寶可夢全數失去戰鬥能力則對戰結束。只有挑戰者可以進行寶可夢的替換");
	pokemon* assign[3] = { &Bergmite,&Avalugg,&Abomasnow };
	my_cout("[德撫]：冰寶，來吧！");
	win_or_lose = whole_battle(3, 3, &Wulfric, assign);
	if (win_or_lose == false) {
		cout << "再鍛鍊鍛鍊寶可夢吧！\n";
		main_menu();
		mission8_4();
	}
	if (missions[7][3].get_complete() == false) {
		my_cout("[對戰裁判員]：這場對戰由挑戰者" + player.get_name() + "獲勝！");
		my_cout("[德撫]：真是場熱血的對戰啊！");
		my_cout("[你]：謝謝你，德撫先生！");
		my_cout("[德撫]：那什麼...這枚徽章就交給你了！");
		my_cout("[獲得獎勵：冰山徽章]");
		player.add_badge(badge("映雪道館", 5));
		player.plus_badgenum();
		my_cout("[你]：謝謝你！");
		my_cout("[德撫]：那什麼...道館徽章集齊了吧！所以接下來就是那...卡洛斯聯盟戰對吧？");
		my_cout("[你]：是！我會努力的！");
		my_cout("[德撫]：那麼，期待你的好表現！");
		my_cout("[你]：謝謝你！");
		my_cout("[希特隆]：我們回密阿雷市吧！");
		my_cout("[你]：嗯？希特隆你們想回家了嗎！");
		my_cout("[希特隆]：啊？");
		my_cout("[柚麗嘉]：才不是呢！聯盟戰就在密阿雷市舉行阿！");
		my_cout("[你]：欸是嗎？");
		my_cout("[柚麗嘉]：" + player.get_name() + "你也真是的");
		my_cout("[你]：好！那我們就去蜜阿雷道館吧！");
		my_cout("[你終於拿到了八枚徽章，與夥伴走來的辛苦總算沒有白費。而你們的旅程還將繼續]");
		my_cout(".\n.\n.\nTo be continued...");
		my_cout("\n[主線8-4 發動巨型水手裡箭 對決超級暴雪王 completed]");
		my_cout("[獲得獎勵：皮幣*500]");
		player.set_money(500);
		my_cout("[寶可夢經驗值上升]");
		minus_health();
		my_cout("[已解鎖 配戴徽章]");
		missions[7][3].set_complete(true);
		current_mission = &missions[8][0];
		confirm_land_conflict();
		main_menu();
	}
}

void mission9_1() {
	enter_mission(8, 0);
	if (missions[8][0].get_start() == false) {
		missions[8][0].set_start(true);
		cin.ignore();
		my_cout("\n~~~~~主線第九章 開始~~~~~");
		my_cout("[柚麗嘉]：這邊這邊！");
		my_cout("[你]：咦？不是在密阿雷道館嗎？");
		my_cout("[希特隆]：不是喔！卡洛斯聯盟有自己的場館，可以容納非常多觀眾，而且每年只有聯盟戰期間才會使用喔！");
		my_cout("[你]：原來如此！");
		my_cout("[柚麗嘉]：快去報到吧！" + player.get_name());
		my_cout("[你]：好！");
		my_cout("[希特隆]：對戰表出來了呢！我看看..." + player.get_name() + "你是第二場，對上一位叫阿朋的訓練家");
		my_cout("[你]：真期待呢！");
		my_cout("[柚麗嘉]：加油！");
		my_cout("[希特隆]：我們先去觀眾席了，" + player.get_name() + "，加油喔！");
		my_cout("[你]：嗯！謝謝你們！");
		my_cout("\n[選手休息區]");
		my_cout("[你]：這裡就是選手休息區了...");
		my_cout("[熟悉男聲]：" + player.get_name() + "！");
		my_cout("[你]：翔太！你是第幾個出場？");
		my_cout("[翔太]：我在你後面呢。你是第二場，很快就要上了呢！");
		my_cout("[你]：突然有些緊張呢...第一場開始了嗎？");
		my_cout("[翔太]：選手已經登場了！那邊有電視轉播，上場前可以看看其他人的比賽");
		my_cout("[播報員]：第一輪32強比賽是1對1賽制。現在，第一場比賽的選手，多羅巴，以及艾嵐選手已經上場了！");
		my_cout("[你]：艾嵐！他果然來了");
		my_cout("[翔太]：他是你的朋友嗎？");
		my_cout("[你]：嗯！他是一個很強的訓練家呢！");
		my_cout("[翔太]：那我得仔細作筆記呢");
		my_cout("[播報員]：多羅巴選手的mega噴火龍噴射火焰擊中，喪失戰鬥能力。本屆賽會第一場勝利由艾嵐選手拿下！");
		my_cout("[翔太]：mega噴火龍對上mega噴火龍...第一場比賽就這麼精采嗎...");
		my_cout("[你]：艾嵐果然贏了呀！翔太，我得去預備席準備囉");
		my_cout("[翔太]：嗯！加油！");
		my_cout("[播報員]：第二場比賽由阿朋選手對上小智選手！兩位選手現在已經登上對戰台了");
		my_cout("[你]：開始囉！");
		my_cout("[對戰裁判員]：對戰開始，請兩位選手派出寶可夢");
	}
	my_cout("\n     [battle v.s. 阿朋]");
	my_cout("[阿朋]：七夕青鳥，上吧！");
	pokemon* assign[1] = { &Altaria };
	win_or_lose = whole_battle(1, 1, &Ahe, assign);
	if (win_or_lose == false) {
		cout << "再鍛鍊鍛鍊寶可夢吧！\n";
		main_menu();
		mission9_1();
	}
	if (missions[8][0].get_complete() == false) {
		my_cout("[對戰裁判員]：這場對戰由挑戰者" + player.get_name() + "獲勝！");
		my_cout("[你]：第一場對戰獲勝了！");
		my_cout("[皮卡丘]：皮卡皮卡！");
		my_cout("[你]：我們還要一直一直在這個舞台戰鬥下去，目標是聯盟冠軍！");
		my_cout(".\n.\n.\nTo be continued...");
		my_cout("\n[主線9-1 聯盟戰第一場 completed]");
		my_cout("[獲得獎勵：厲害傷藥*10]");
		player.get_consumable(9)->add_num(10);
		my_cout("[寶可夢經驗值上升]");
		minus_health();
		missions[8][0].set_complete(true);
		current_mission = &missions[8][1];
		confirm_land_conflict();
		main_menu();
	}
}
void mission9_2() {//最強挑戰者 勁敵對決
	enter_mission(8, 1);
	if (missions[8][1].get_start() == false) {
		missions[8][1].set_start(true);
		cin.ignore();
		my_cout("[你延續著第一場比賽獲勝的氣勢，一路過關斬將贏到八強戰]");
		my_cout("\n[賽場觀眾席]");
		my_cout("[你]：今天也獲勝了呢！");
		my_cout("[皮卡丘]：皮卡皮卡！");
		my_cout("[翔太]：" + player.get_name() + "！");
		my_cout("[你]：翔太！恭喜你也獲勝了！");
		my_cout("[翔太]：謝謝！");
		my_cout("[希特隆]：待會八強的最後一場比賽結束後，對戰表就會直接公布了");
		my_cout("[播報員]：四強的最後一個名額出來了！是艾嵐選手");
		my_cout("[播報員]：同時！四強的對戰組合也即將出爐，讓我們看向大螢幕");
		my_cout("[播報員]：第一場，艾嵐選手對上路易選手；第二場，" + player.get_name() + "選手對上翔太選手");
		my_cout("[播報員]：請大家明天繼續為訓練家們加油！");
		my_cout("[你]：就是明天了呢！翔太");
		my_cout("[翔太]：嗯！我會全力以赴的！");
		my_cout("[你]：我也是！");
		my_cout("\n[隔天，賽場]");
		my_cout("[播報員]：繼剛剛的第一位決賽晉級者：艾嵐獲勝，四強戰第二場比賽即將開始！究竟是哪位選手會脫穎而出呢？讓我們拭目以待！");
		my_cout("[對戰裁判員]：四強戰可使用的寶可夢為六隻，若有一方的寶可夢全數失去戰鬥能力則對戰結束。");
		my_cout("[對戰裁判員]：那麼，對戰開始！請兩位選手派出寶可夢");
	}
	my_cout("\n     [battle v.s. 翔太]");
	Sceptile.set_mega_ability(true);
	pokemon* assign[6] = { &Slaking,&Clawitzer,&Aegislash,&Salamence,&Slurpuff,&Sceptile };
	my_cout("[翔太]：第一個就是你了！請假王！");
	win_or_lose = whole_battle(6, 6, &Sawyer, assign);
	if (win_or_lose == false) {
		cout << "再鍛鍊鍛鍊寶可夢吧！\n";
		main_menu();
		mission9_2();
	}
	if (missions[8][1].get_complete() == false) {
		my_cout("[對戰裁判員]：這場對戰由挑戰者" + player.get_name() + "獲勝！");
		my_cout("[你]：贏了！");
		my_cout("[皮卡丘]：皮卡皮卡！");
		my_cout("[翔太]：蜥蜴王，辛苦了");
		my_cout("[你]：翔太！");
		my_cout("[翔太]：恭喜你！這是一場精采的比賽");
		my_cout("[你]：謝謝你！");
		my_cout("[翔太]：話是這麼說...但我還是好不甘心啊...");
		my_cout("[你]：翔太...");
		my_cout("[翔太]：決賽，要贏喔！我會在旁邊親眼見證的");
		my_cout("[你]：嗯！我會贏的！");
		my_cout(".\n.\n.\nTo be continued...");
		my_cout("\n[主線9-2 最強挑戰者 勁敵對決 completed]");
		my_cout("[獲得獎勵：厲害傷藥*10]");
		player.get_consumable(9)->add_num(10);
		my_cout("[寶可夢經驗值上升]");
		minus_health();
		missions[8][1].set_complete(true);
		current_mission = &missions[8][2];
		confirm_land_conflict();
		main_menu();
	}
}
void mission9_3() {//水火不容 最後的誓言之戰
	enter_mission(8, 2);
	if (missions[8][2].get_start() == false) {
		missions[8][2].set_start(true);
		cin.ignore();
		my_cout("[你]：今天就是決賽了呢！");
		my_cout("[希特隆]：上場吧！相信自己，你可以的");
		my_cout("[你]：嗯！謝謝！");
		my_cout("[柚麗嘉]：加油！" + player.get_name() + "拿下勝利吧！");
		my_cout("[你]：各位，謝謝你們一路陪我走到這裡。決賽...也同樣拜託了！");
		my_cout("[皮卡丘]：皮卡皮卡！");
		my_cout("[甲賀忍蛙]：geko！");
		my_cout("[火箭雀]：yama！");
		my_cout("[摔跤鷹人]：cholu！");
		my_cout("[黏美露龍]：nelo！");
		my_cout("[音波龍]：bua！");
		my_cout("[你]：一起贏下這場比賽吧！");
		my_cout("[播報員]：決賽選手是艾嵐選手與" + player.get_name() + "選手！");
		my_cout("[播報員]：請兩位選手上場！");
		my_cout("[對戰裁判員]：決賽選手可使用的寶可夢為六隻，若有一方的寶可夢全數失去戰鬥能力則對戰結束。");
		my_cout("[對戰裁判員]：那麼，卡洛斯聯盟決賽，對戰開始！請兩位選手派出寶可夢");
	}
	my_cout("\n     [battle v.s. 艾嵐]");
	my_cout("[艾嵐]：出來吧！班基拉斯！");
	pokemon* assign[6] = { &Tyranitar,&Weavile,&Bisharp,&Unfezant,&Metagross,&Charizard };
	win_or_lose = whole_battle(6, 6, &Alain, assign);
	if (win_or_lose == false) {
		cout << "再鍛鍊鍛鍊寶可夢吧！\n";
		main_menu();
		mission9_3();
	}
	if (missions[8][2].get_complete() == false) {
		my_cout("[對戰裁判員]：這場對戰由挑戰者" + player.get_name() + "獲勝！");
		my_cout("[對戰裁判員]：在此宣布！今年得卡洛斯聯盟冠軍是  "+player.get_name());
		my_cout("[你]：贏了！");
		my_cout("[艾嵐]：辛苦了，噴火龍，你做得很好");
		my_cout("[艾嵐]：" + player.get_name() + "，恭喜！你很強！");
		my_cout("[你]：不，這都是我跟夥伴們齊心協力的結果");
		my_cout("[你]：謝謝你，艾嵐！真的很高興能跟你對戰");
		my_cout("[艾嵐]：我也是！這是一場很棒的比賽！");
		my_cout("[希特隆、柚麗嘉]：" + player.get_name() + "！");
		my_cout("[你]：希特隆、柚麗嘉！");
		my_cout("[希特隆]：恭喜你！你是我們的驕傲！");
		my_cout("[你]：希特隆...你怎麼哭啦！");
		my_cout("[柚麗嘉]：哥哥只是太感動啦！");
		my_cout("[眾人]：哈哈哈哈哈哈！");
		my_cout("[卡洛斯聯盟戰智此告一段落，你也拿下夢寐以求的冠軍。但這並不是結束，你與夥伴們的旅程還將繼續]");
		my_cout(".\n.\n.\nTo be continued...");
		my_cout("\n[主線9-3 水火不容 最後的誓言之戰 completed]");
		missions[8][2].set_complete(true);
	}
}

void ending() {
	cout << "\n人類和寶可夢互相協調，組成了這個世界\n人們微笑的話，寶可夢也會微笑\n寶可夢難過時，人們也會難過\n\n這裡是卡洛斯地區，也是你帶給你許多美好回憶的地方。\n\n";
	my_cout("（按enter鍵繼續）");
	my_cout("\n[你]：皮卡丘，我們回家吧！");
	my_cout("[皮卡丘]：皮卡皮卡");
	my_cout("\n~~~~故事結束~~~~");
}

void use_my_pokemon_ball() {
	int choose = 2;
	while (choose != 1) {
		cout << "是否使用寶貝球，收服寶可夢？（1：是，2：否）："; cin >> choose;
		if (choose == 1) {
			player.use_ball();
			break;
		}
		cout << "這是唯一的機會收服這隻寶可夢，不收服寶可夢會對未來的遊戲進行造成影響，請謹慎選擇\n";
	}
}